/** @file proto_schema.gen.h
 * Auto-generated by scripts/gen_schema.py from proto_schema.json -- do not edit. */
#ifndef PROTO_SCHEMA_GEN_H
#define PROTO_SCHEMA_GEN_H

#include "codec/json.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/** @name Struct types
 *  @{ */

struct json_proto_extensions {
	struct json_string identity;

	bool reject_inbound;
};

struct json_proto {
	struct json_proto_extensions extensions;

	struct json_string session_id;
	struct json_string type;

	unsigned resume_seq;

	intmax_t msgid;
};

/** @} */

/** @name Unmarshal
 *  @{ */

/**
 * @brief Unmarshal JSON into *obj; modifies @p json in place.
 * @param obj Output; zeroed and given schema defaults before parsing.
 * @param json Mutable JSON; @p obj aliases it, so keep it valid in use.
 * @param length Length of @p json in bytes.
 * @return true on success; on failure, false and *obj reset to all-zero.
 */
bool json_unmarshal_proto(
	struct json_proto *obj, char *json, size_t length);

/** @} */

/** @name Marshal
 *  @{ */

/**
 * @brief Marshal *obj into @p buf as JSON (snprintf semantics).
 * @param buf Output buffer, or NULL to only compute the size.
 * @param bufsz Size of @p buf in bytes.
 * @param obj Object to encode.
 * @param indent Per-level indent for pretty output, or NULL for compact.
 * @return Byte length excluding NUL (truncates if >= @p bufsz), or -1 on error.
 */
int json_marshal_proto(
	char *buf, size_t bufsz, const struct json_proto *obj, const char *indent);

/** @} */

/** @name Free
 *  @{ */

/** @brief Free heap-allocated fields inside *obj (arrays). */
void json_free_proto(struct json_proto *obj);

/** @} */

#endif /* PROTO_SCHEMA_GEN_H */
