/** @file proto_schema.gen.h
 * Auto-generated by scripts/gen_schema.py from proto_schema.json -- do not edit. */
#ifndef PROTO_SCHEMA_GEN_H
#define PROTO_SCHEMA_GEN_H

#include "codec/json.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/** @name Struct types
 *  @{ */

struct json_proto_extensions {
	struct json_string identity;

	bool reject_inbound;
};

struct json_proto {
	struct json_proto_extensions extensions;

	struct json_string session_id;
	struct json_string type;

	unsigned resume_seq;

	intmax_t msgid;
};

/** @} */

/** @name Unmarshal
 *  @{ */

/* Unmarshal json (length bytes) into *obj; the buffer is modified in-place. */
/* The function zero-initializes *obj and applies schema defaults before parsing; pointer fields of set keys then point into the json buffer (keep it valid). Returns true on success. */
bool json_unmarshal_proto(
	struct json_proto *obj, char *json, size_t length);

/** @} */

/** @name Marshal
 *  @{ */

/* Marshal *obj into buf as JSON text (snprintf semantics: returns chars written
   excluding NUL, or required size including NUL when buf is NULL or bufsz is 0). */
int json_marshal_proto(char *buf, size_t bufsz, const struct json_proto *obj);

/** @} */

/** @name Free
 *  @{ */

/* Free heap-allocated fields inside *obj (arrays). */
void json_free_proto(struct json_proto *obj);

/** @} */

#endif /* PROTO_SCHEMA_GEN_H */
