/** @file proto_schema.gen.c
 * Auto-generated by scripts/gen_schema.py from proto_schema.json -- do not edit. */
#include "proto_schema.gen.h"

#include "codec/json.h"

#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/** @name Key tables
 *  @{ */

/* --- json_proto --- */
static int
json_lookup_proto(const char *str, size_t len)
{
	if (len < 1) { return -1; }
	switch ((unsigned char)str[0]) {
	case 'e':
		return len == 10 && memcmp(str, "extensions", 10) == 0 ? 0 : -1;
	case 'm':
		return len == 5 && memcmp(str, "msgid", 5) == 0 ? 1 : -1;
	case 'r':
		return len == 10 && memcmp(str, "resume_seq", 10) == 0 ? 2 : -1;
	case 's':
		return len == 10 && memcmp(str, "session_id", 10) == 0 ? 3 : -1;
	case 't':
		return len == 4 && memcmp(str, "type", 4) == 0 ? 4 : -1;
	default: return -1;
	}
}

/* --- json_proto_extensions --- */
static int
json_lookup_proto_extensions(const char *str, size_t len)
{
	if (len < 1) { return -1; }
	switch ((unsigned char)str[0]) {
	case 'i':
		return len == 8 && memcmp(str, "identity", 8) == 0 ? 0 : -1;
	case 'r':
		return len == 14 && memcmp(str, "reject_inbound", 14) == 0 ? 1 : -1;
	default: return -1;
	}
}

/** @} */

/** @name Key indices
 *  @{ */

enum json_proto_key {
	JSON_PROTO_EXTENSIONS = 0,
	JSON_PROTO_MSGID = 1,
	JSON_PROTO_RESUME_SEQ = 2,
	JSON_PROTO_SESSION_ID = 3,
	JSON_PROTO_TYPE = 4,
};

enum json_proto_extensions_key {
	JSON_PROTO_EXTENSIONS_IDENTITY = 0,
	JSON_PROTO_EXTENSIONS_REJECT_INBOUND = 1,
};

/** @} */

/** @name Free
 *  @{ */

static void json_free_proto_extensions(struct json_proto_extensions *obj)
{
	(void)obj;
}

void json_free_proto(struct json_proto *obj)
{
	json_free_proto_extensions(&obj->extensions);
}

/** @} */

/** @name Unmarshal
 *  @{ */

static bool json_unmarshal_proto_extensions(
	struct json_proto_extensions *obj, char *json, size_t length)
{
	*obj = (struct json_proto_extensions){
		.reject_inbound = false,
	};
	const struct json_val root_ = json_parse(json, &(size_t){ length });
	if (root_.type != JSON_OBJECT) { return false; }
	json_iter iter_ = root_.iter;
	char *key_; size_t key_len_; char *val_; size_t val_len_;
	int next_;

	while ((next_ = json_obj_next(json, &length, &iter_,
			&key_, &key_len_, &val_, &val_len_)) == JSON_NEXT_ITEM) {
		const int k_ = json_lookup_proto_extensions(key_, key_len_);
		switch (k_) {
		case JSON_PROTO_EXTENSIONS_IDENTITY: {
			if (!json_parse_string(val_, val_len_, &obj->identity.str, &obj->identity.len)) { goto fail_; }
			if (obj->identity.len > 255u) { goto fail_; }
			break;
		}
		case JSON_PROTO_EXTENSIONS_REJECT_INBOUND: {
			if (!json_parse_bool(val_, val_len_, &obj->reject_inbound)) { goto fail_; }
			break;
		}
		default:
			break;
		}
	}
	if (next_ != JSON_NEXT_END) { goto fail_; }
	for (; iter_ < length; iter_++) {
		if (!json_iswhitespace(json[iter_])) { goto fail_; }
	}
	return true;

fail_:
	json_free_proto_extensions(obj);
	*obj = (struct json_proto_extensions){ 0 };
	return false;
}

bool json_unmarshal_proto(
	struct json_proto *obj, char *json, size_t length)
{
	*obj = (struct json_proto){
		.extensions = {
			.reject_inbound = false,
		},
	};
	const struct json_val root_ = json_parse(json, &(size_t){ length });
	if (root_.type != JSON_OBJECT) { return false; }
	json_iter iter_ = root_.iter;
	char *key_; size_t key_len_; char *val_; size_t val_len_;
	uint_fast64_t required_ = 0;
	int next_;

	while ((next_ = json_obj_next(json, &length, &iter_,
			&key_, &key_len_, &val_, &val_len_)) == JSON_NEXT_ITEM) {
		const int k_ = json_lookup_proto(key_, key_len_);
		switch (k_) {
		case JSON_PROTO_EXTENSIONS: {
			/* duplicate key: release the previous value first */
			json_free_proto_extensions(&obj->extensions);
			if (!json_unmarshal_proto_extensions(&obj->extensions, val_, val_len_)) {
				goto fail_;
			}
			break;
		}
		case JSON_PROTO_MSGID: {
			if (!json_parse_imax(val_, val_len_, &obj->msgid)) { goto fail_; }
			if (obj->msgid != INTMAX_C(0) && obj->msgid != INTMAX_C(1)) { goto fail_; }
			required_ |= UINT64_C(1) << 0;
			break;
		}
		case JSON_PROTO_RESUME_SEQ: {
			if (!json_parse_uint(val_, val_len_, &obj->resume_seq)) { goto fail_; }
			break;
		}
		case JSON_PROTO_SESSION_ID: {
			if (!json_parse_string(val_, val_len_, &obj->session_id.str, &obj->session_id.len)) { goto fail_; }
			if (obj->session_id.len < 24u) { goto fail_; }
			if (obj->session_id.len > 24u) { goto fail_; }
			break;
		}
		case JSON_PROTO_TYPE: {
			if (!json_parse_string(val_, val_len_, &obj->type.str, &obj->type.len)) { goto fail_; }
			required_ |= UINT64_C(1) << 1;
			break;
		}
		default:
			break;
		}
	}
	if (next_ != JSON_NEXT_END) { goto fail_; }
	if (required_ != UINT64_C(0x3)) { goto fail_; }
	for (; iter_ < length; iter_++) {
		if (!json_iswhitespace(json[iter_])) { goto fail_; }
	}
	return true;

fail_:
	json_free_proto(obj);
	*obj = (struct json_proto){ 0 };
	return false;
}

/** @} */

/** @name Marshal
 *  @{ */

static int json_checked_int_(size_t n_)
{
	if (n_ > (size_t)INT_MAX) { return -1; }
	return (int)n_;
}
static size_t json_emit_ch_(char *buf, size_t bufsz, size_t n_, char c)
{
	if (buf != NULL && n_ < bufsz) { buf[n_] = c; }
	return n_ + 1;
}
static size_t json_emit_raw_(
	char *buf, size_t bufsz, size_t n_, const char *s, size_t len)
{
	if (buf != NULL && n_ < bufsz) {
		const size_t cap_ = bufsz - n_;
		memcpy(buf + n_, s, len < cap_ ? len : cap_);
	}
	return n_ + len;
}
static size_t json_emit_str_(
	char *buf, size_t bufsz, size_t n_, const char *s, size_t len)
{
	char *dst_ = (buf != NULL && n_ < bufsz) ? buf + n_ : NULL;
	const int r_ =
		json_marshal_string(dst_, dst_ != NULL ? bufsz - n_ : 0, s, len);
	if (r_ < 0) { return SIZE_MAX; }
	return n_ + (size_t)r_;
}
static size_t json_emit_indent_(
	char *buf, size_t bufsz, size_t n_, const char *indent,
	size_t ind_len_, int d)
{
	if (indent == NULL) { return n_; }
	n_ = json_emit_ch_(buf, bufsz, n_, '\n');
	for (int id_ = 0; id_ < d; id_++) {
		n_ = json_emit_raw_(buf, bufsz, n_, indent, ind_len_);
	}
	return n_;
}

#define EMIT(c) do { n_ = json_emit_ch_(buf, bufsz, n_, (char)(c)); } while (0)
#define EMITF(fmt, ...) do { \
	char *dst_ = (buf != NULL && n_ < bufsz) ? buf + n_ : NULL; \
	r_ = snprintf(dst_, dst_ != NULL ? bufsz - n_ : 0, fmt, __VA_ARGS__); \
	if (r_ < 0) { return SIZE_MAX; } \
	n_ += (size_t)r_; \
} while (0)
#define EMIT_STR(s, len) do { \
	n_ = json_emit_str_(buf, bufsz, n_, (s), (len)); \
	if (n_ == SIZE_MAX) { return SIZE_MAX; } \
} while (0)
#define EMIT_SUB(fn, arg, d) do { \
	char *dst_ = (buf != NULL && n_ < bufsz) ? buf + n_ : NULL; \
	const size_t rsub_ = (fn)(dst_, dst_ != NULL ? bufsz - n_ : 0, (arg), indent, (d)); \
	if (rsub_ == SIZE_MAX) { return SIZE_MAX; } \
	n_ += rsub_; \
} while (0)
#define EMIT_LIT(s) do { \
	static const char lit_[] = s; \
	n_ = json_emit_raw_(buf, bufsz, n_, lit_, sizeof(lit_) - 1); \
} while (0)
#define EMIT_RAW(s, len) do { \
	n_ = json_emit_raw_(buf, bufsz, n_, (s), (len)); \
} while (0)
#define EMIT_INDENT(d) do { \
	n_ = json_emit_indent_(buf, bufsz, n_, indent, ind_len_, (d)); \
} while (0)
#define EMIT_COLON() do { \
	EMIT(':'); \
	if (indent != NULL) { EMIT(' '); } \
} while (0)

static size_t json_marshal_proto_extensions_impl(
	char *buf, size_t bufsz, const struct json_proto_extensions *obj,
	const char *indent, int depth)
{
	size_t n_ = 0;
	int r_ = 0;
	(void)r_;
	const size_t ind_len_ = (indent != NULL) ? strlen(indent) : 0;
	(void)ind_len_;
	(void)depth;

	EMIT('{');
	const size_t n_start_ = n_;

	if (obj->identity.str != NULL) {
		EMIT_INDENT(depth + 1);
		EMIT('"');
		EMIT_LIT("identity");
		EMIT('"');
		EMIT_COLON();
		EMIT_STR(obj->identity.str, obj->identity.len);
		EMIT(',');
	}
	EMIT_INDENT(depth + 1);
	EMIT('"');
	EMIT_LIT("reject_inbound");
	EMIT('"');
	EMIT_COLON();
	if (obj->reject_inbound) {
		EMIT_LIT("true");
	} else {
		EMIT_LIT("false");
	}
	EMIT(',');

	if (n_ > n_start_) {
		n_--;
		EMIT_INDENT(depth);
	}
	EMIT('}');
	if (buf != NULL && bufsz > 0) {
		buf[n_ < bufsz ? n_ : bufsz - 1] = '\0';
	}

	return n_;
}

static size_t json_marshal_proto_impl(
	char *buf, size_t bufsz, const struct json_proto *obj,
	const char *indent, int depth)
{
	size_t n_ = 0;
	int r_ = 0;
	(void)r_;
	const size_t ind_len_ = (indent != NULL) ? strlen(indent) : 0;
	(void)ind_len_;
	(void)depth;

	EMIT('{');
	const size_t n_start_ = n_;

	EMIT_INDENT(depth + 1);
	EMIT('"');
	EMIT_LIT("extensions");
	EMIT('"');
	EMIT_COLON();
	EMIT_SUB(json_marshal_proto_extensions_impl, &obj->extensions, depth + 1);
	EMIT(',');
	EMIT_INDENT(depth + 1);
	EMIT('"');
	EMIT_LIT("msgid");
	EMIT('"');
	EMIT_COLON();
	EMITF("%jd", (intmax_t)obj->msgid);
	EMIT(',');
	EMIT_INDENT(depth + 1);
	EMIT('"');
	EMIT_LIT("resume_seq");
	EMIT('"');
	EMIT_COLON();
	EMITF("%u", obj->resume_seq);
	EMIT(',');
	if (obj->session_id.str != NULL) {
		EMIT_INDENT(depth + 1);
		EMIT('"');
		EMIT_LIT("session_id");
		EMIT('"');
		EMIT_COLON();
		EMIT_STR(obj->session_id.str, obj->session_id.len);
		EMIT(',');
	}
	EMIT_INDENT(depth + 1);
	EMIT('"');
	EMIT_LIT("type");
	EMIT('"');
	EMIT_COLON();
	if (obj->type.str != NULL) {
		EMIT_STR(obj->type.str, obj->type.len);
	} else {
		EMIT_LIT("\"\"");
	}
	EMIT(',');

	if (n_ > n_start_) {
		n_--;
		EMIT_INDENT(depth);
	}
	EMIT('}');
	if (buf != NULL && bufsz > 0) {
		buf[n_ < bufsz ? n_ : bufsz - 1] = '\0';
	}

	return n_;
}

int json_marshal_proto(
	char *buf, size_t bufsz, const struct json_proto *obj,
	const char *indent)
{
	return json_checked_int_(
		json_marshal_proto_impl(buf, bufsz, obj, indent, 0));
}


#undef EMIT
#undef EMITF
#undef EMIT_STR
#undef EMIT_SUB
#undef EMIT_LIT
#undef EMIT_RAW
#undef EMIT_INDENT
#undef EMIT_COLON

/** @} */
