/** @file proto_schema.gen.c
 * Auto-generated by scripts/gen_schema.py from proto_schema.json -- do not edit. */
#include "proto_schema.gen.h"

#include "codec/json.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/** @name Key tables
 *  @{ */

/* --- json_proto --- */
static int
json_proto_lookup(const char *str, size_t len)
{
    if (len < 1) { return -1; }
    switch ((unsigned char)str[0]) {
    case 'e':
        return len == 10 && memcmp(str, "extensions", 10) == 0 ? 0 : -1;
    case 'm':
        return len == 5 && memcmp(str, "msgid", 5) == 0 ? 1 : -1;
    case 'r':
        return len == 10 && memcmp(str, "resume_seq", 10) == 0 ? 2 : -1;
    case 's':
        return len == 10 && memcmp(str, "session_id", 10) == 0 ? 3 : -1;
    case 't':
        return len == 4 && memcmp(str, "type", 4) == 0 ? 4 : -1;
    default: return -1;
    }
}

/* --- json_proto_extensions --- */
static int
json_proto_extensions_lookup(const char *str, size_t len)
{
    if (len < 1) { return -1; }
    switch ((unsigned char)str[0]) {
    case 'i':
        return len == 8 && memcmp(str, "identity", 8) == 0 ? 0 : -1;
    case 'r':
        return len == 14 && memcmp(str, "reject_inbound", 14) == 0 ? 1 : -1;
    default: return -1;
    }
}

/** @} */

/** @name Key indices
 *  @{ */

enum json_proto_key {
    JSON_PROTO_EXTENSIONS = 0,
    JSON_PROTO_MSGID = 1,
    JSON_PROTO_RESUME_SEQ = 2,
    JSON_PROTO_SESSION_ID = 3,
    JSON_PROTO_TYPE = 4,
};

enum json_proto_extensions_key {
    JSON_PROTO_EXTENSIONS_IDENTITY = 0,
    JSON_PROTO_EXTENSIONS_REJECT_INBOUND = 1,
};

/** @} */

/** @name Free
 *  @{ */

static void json_proto_extensions_free(struct json_proto_extensions *obj)
{
    (void)obj;
}

void json_proto_free(struct json_proto *obj)
{
    json_proto_extensions_free(&obj->extensions);
}

/** @} */

/** @name Unmarshal
 *  @{ */

static bool json_proto_extensions_unmarshal(
    struct json_proto_extensions *obj, char *json, size_t length)
{
    const struct json_val root_ = json_parse(json, length);
    if (root_.type != JSON_OBJECT) { return false; }
    json_iter iter_ = root_.iter;
    char *key_; size_t key_len_; char *val_; size_t val_len_;
    while (json_obj_next(json, length, &iter_,
            &key_, &key_len_, &val_, &val_len_)) {
        const int k_ = json_proto_extensions_lookup(key_, key_len_);
        switch (k_) {
        case JSON_PROTO_EXTENSIONS_IDENTITY: {
            if (!json_parse_string(val_, val_len_, &obj->identity, &obj->identity_len)) { return false; }
            break;
        }
        case JSON_PROTO_EXTENSIONS_REJECT_INBOUND: {
            { bool bv_;
            if (!json_parse_bool(val_, val_len_, &bv_)) { return false; }
            obj->reject_inbound = bv_; obj->has_reject_inbound = true; }
            break;
        }
        default:
            break;
        }
    }
    return true;
}

bool json_proto_unmarshal(
    struct json_proto *obj, char *json, size_t length)
{
    const struct json_val root_ = json_parse(json, length);
    if (root_.type != JSON_OBJECT) { return false; }
    json_iter iter_ = root_.iter;
    char *key_; size_t key_len_; char *val_; size_t val_len_;
    while (json_obj_next(json, length, &iter_,
            &key_, &key_len_, &val_, &val_len_)) {
        const int k_ = json_proto_lookup(key_, key_len_);
        switch (k_) {
        case JSON_PROTO_EXTENSIONS: {
            if (!json_proto_extensions_unmarshal(&obj->extensions, val_, val_len_)) {
                return false;
            }
            obj->has_extensions = true;
            break;
        }
        case JSON_PROTO_MSGID: {
            if (!json_parse_imax(val_, val_len_, &obj->msgid)) { return false; }
            obj->has_msgid = true;
            break;
        }
        case JSON_PROTO_RESUME_SEQ: {
            if (!json_parse_uint(val_, val_len_, &obj->resume_seq)) { return false; }
            obj->has_resume_seq = true;
            break;
        }
        case JSON_PROTO_SESSION_ID: {
            if (!json_parse_string(val_, val_len_, &obj->session_id, &obj->session_id_len)) { return false; }
            break;
        }
        case JSON_PROTO_TYPE: {
            if (!json_parse_string(val_, val_len_, &obj->type, &obj->type_len)) { return false; }
            break;
        }
        default:
            break;
        }
    }
    if (!obj->has_msgid) { return false; }
    if (obj->type == NULL) { return false; }
    return true;
}

/** @} */

/** @name Marshal
 *  @{ */

#define EMIT(fmt, ...) do { \
    r_ = snprintf(buf ? buf + n_ : NULL, \
        bufsz > (size_t)n_ ? bufsz - (size_t)n_ : 0, fmt, __VA_ARGS__); \
    if (r_ < 0) { return -1; } \
    n_ += r_; \
} while (0)
#define EMIT_STR(s, len) do { \
    r_ = json_marshal_string(buf ? buf + n_ : NULL, \
        bufsz > (size_t)n_ ? bufsz - (size_t)n_ : 0, (s), (len)); \
    if (r_ < 0) { return -1; } \
    n_ += r_; \
} while (0)
#define EMIT_SUB(fn, arg) do { \
    r_ = (fn)(buf ? buf + n_ : NULL, \
        bufsz > (size_t)n_ ? bufsz - (size_t)n_ : 0, (arg)); \
    if (r_ < 0) { return -1; } \
    n_ += r_; \
} while (0)

static int json_proto_extensions_marshal(
    char *buf, size_t bufsz, const struct json_proto_extensions *obj)
{
    int n_ = 0;
    int r_;
    bool first_ = true;

    EMIT("%s", "{");

    if (obj->identity != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "identity");
        first_ = false;
        EMIT_STR(obj->identity, obj->identity_len);
    }
    if (obj->has_reject_inbound) {
        EMIT("%s\"%s\":%s", first_ ? "" : ",", "reject_inbound",
            obj->reject_inbound ? "true" : "false");
        first_ = false;
    }

    EMIT("%s", "}");

    return n_;
}

int json_proto_marshal(
    char *buf, size_t bufsz, const struct json_proto *obj)
{
    int n_ = 0;
    int r_;
    bool first_ = true;

    EMIT("%s", "{");

    if (obj->has_extensions) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "extensions");
        first_ = false;
        EMIT_SUB(json_proto_extensions_marshal, &obj->extensions);
    }
    EMIT("%s\"%s\":%jd", first_ ? "" : ",", "msgid",
        (intmax_t)obj->msgid);
    first_ = false;
    if (obj->has_resume_seq) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "resume_seq",
            (uintmax_t)obj->resume_seq);
        first_ = false;
    }
    if (obj->session_id != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "session_id");
        first_ = false;
        EMIT_STR(obj->session_id, obj->session_id_len);
    }
    if (obj->type != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "type");
        first_ = false;
        EMIT_STR(obj->type, obj->type_len);
    }

    EMIT("%s", "}");

    return n_;
}


#undef EMIT
#undef EMIT_STR
#undef EMIT_SUB

/** @} */
