/** @file conf_schema.gen.c
 * Auto-generated by scripts/gen_schema.py from conf_schema.json -- do not edit. */
#include "conf_schema.gen.h"

#include "codec/json.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/** @name Key tables
 *  @{ */

/* --- json_conf --- */
/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: gperf -l -c -E -P -Qjson_lookup_conf_stringpool --null-strings --initializer-suffix=,0  */
/* Computed positions: -k'2,6' */



/* json_lookup_conf: 13 keys  (auto-generated -- do not edit) */
struct json_lookup_conf_kv { int name; int idx; };
/* maximum key range = 21, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
json_lookup_conf_hash (register const char *str, register size_t len)
{
	(void)(str);
  static const unsigned char asso_values[] =
    {
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24,  5, 24,  5,
      15,  5, 24, 24, 24,  0, 24, 24, 15, 24,
       0,  0,  5, 24, 24, 24,  0,  0,  5, 24,
      24,  0, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
      24, 24, 24, 24, 24, 24
    };
  register unsigned int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
      case 4:
      case 3:
      case 2:
        hval += asso_values[(unsigned char)str[1]];
        break;
    }
  return hval;
}

struct json_lookup_conf_stringpool_t
  {
    char json_lookup_conf_stringpool_str3[sizeof("mux")];
    char json_lookup_conf_stringpool_str4[sizeof("type")];
    char json_lookup_conf_stringpool_str6[sizeof("listen")];
    char json_lookup_conf_stringpool_str8[sizeof("tcp")];
    char json_lookup_conf_stringpool_str10[sizeof("mux_listen")];
    char json_lookup_conf_stringpool_str11[sizeof("mux_connect")];
    char json_lookup_conf_stringpool_str12[sizeof("connect")];
    char json_lookup_conf_stringpool_str13[sizeof("loglevel")];
    char json_lookup_conf_stringpool_str15[sizeof("api_listen")];
    char json_lookup_conf_stringpool_str17[sizeof("max_startups")];
    char json_lookup_conf_stringpool_str18[sizeof("tls")];
    char json_lookup_conf_stringpool_str22[sizeof("max_sessions")];
    char json_lookup_conf_stringpool_str23[sizeof("identity")];
  };
static const struct json_lookup_conf_stringpool_t json_lookup_conf_stringpool_contents =
  {
    "mux",
    "type",
    "listen",
    "tcp",
    "mux_listen",
    "mux_connect",
    "connect",
    "loglevel",
    "api_listen",
    "max_startups",
    "tls",
    "max_sessions",
    "identity"
  };
#define json_lookup_conf_stringpool ((const char *) &json_lookup_conf_stringpool_contents)
static const struct json_lookup_conf_kv *
json_lookup_conf_kv_lookup_ (register const char *str, register size_t len)
{
  enum
    {
      TOTAL_KEYWORDS = 13,
      MIN_WORD_LENGTH = 3,
      MAX_WORD_LENGTH = 12,
      MIN_HASH_VALUE = 3,
      MAX_HASH_VALUE = 23
    };

  static const unsigned char lengthtable[] =
    {
       0,  0,  0,  3,  4,  0,  6,  0,  3,  0, 10, 11,  7,  8,
       0, 10,  0, 12,  3,  0,  0,  0, 12,  8
    };
  static const struct json_lookup_conf_kv wordlist[] =
    {
      {-1,0}, {-1,0}, {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str3, 7},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str4, 12},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str6, 3},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str8, 10},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str10, 9},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str11, 8},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str12, 1},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str13, 4},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str15, 0},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str17, 6},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str18, 11},
      {-1,0}, {-1,0}, {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str22, 5},
      {(int)(size_t)&((struct json_lookup_conf_stringpool_t *)0)->json_lookup_conf_stringpool_str23, 2}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = json_lookup_conf_hash (str, len);

      if (key <= MAX_HASH_VALUE)
        if (len == lengthtable[key])
          {
            register const char *s = wordlist[key].name + json_lookup_conf_stringpool;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &wordlist[key];
          }
    }
  return 0;
}


#ifdef TOTAL_KEYWORDS
#undef TOTAL_KEYWORDS
#endif
#ifdef MIN_WORD_LENGTH
#undef MIN_WORD_LENGTH
#endif
#ifdef MAX_WORD_LENGTH
#undef MAX_WORD_LENGTH
#endif
#ifdef MIN_HASH_VALUE
#undef MIN_HASH_VALUE
#endif
#ifdef MAX_HASH_VALUE
#undef MAX_HASH_VALUE
#endif

static int
json_lookup_conf(const char *str, size_t len)
{
	const struct json_lookup_conf_kv *kv_ = json_lookup_conf_kv_lookup_(str, len);
	return kv_ ? kv_->idx : -1;
}

/* --- json_conf_identity --- */
static int
json_lookup_conf_identity(const char *str, size_t len)
{
	if (len < 1) { return -1; }
	switch ((unsigned char)str[0]) {
	case 'a':
		return len == 9 && memcmp(str, "authcerts", 9) == 0 ? 0 : -1;
	case 'c':
		return len == 5 && memcmp(str, "claim", 5) == 0 ? 1 : -1;
	case 'l':
		return len == 6 && memcmp(str, "listen", 6) == 0 ? 2 : -1;
	case 'm':
		return len == 11 && memcmp(str, "mux_connect", 11) == 0 ? 3 : -1;
	default: return -1;
	}
}

/* --- json_conf_mux --- */
/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: gperf -l -c -E -P -Qjson_lookup_conf_mux_stringpool --null-strings --initializer-suffix=,0  */
/* Computed positions: -k'1-2' */



/* json_lookup_conf_mux: 13 keys  (auto-generated -- do not edit) */
struct json_lookup_conf_mux_kv { int name; int idx; };
/* maximum key range = 30, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
json_lookup_conf_mux_hash (register const char *str, register size_t len)
{
	(void)(str);
  static const unsigned char asso_values[] =
    {
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33,  5, 33,  0,
      10,  0, 33, 33, 33, 10, 33,  0, 33,  5,
       0,  0,  5, 33,  5,  0,  0, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
      33, 33, 33, 33, 33, 33
    };
  return len + asso_values[(unsigned char)str[1]] + asso_values[(unsigned char)str[0]];
}

struct json_lookup_conf_mux_stringpool_t
  {
    char json_lookup_conf_mux_stringpool_str3[sizeof("tcp")];
    char json_lookup_conf_mux_stringpool_str7[sizeof("nodelay")];
    char json_lookup_conf_mux_stringpool_str9[sizeof("keepalive")];
    char json_lookup_conf_mux_stringpool_str12[sizeof("send_timeout")];
    char json_lookup_conf_mux_stringpool_str13[sizeof("stream_window")];
    char json_lookup_conf_mux_stringpool_str14[sizeof("session_window")];
    char json_lookup_conf_mux_stringpool_str15[sizeof("connect_timeout")];
    char json_lookup_conf_mux_stringpool_str17[sizeof("mem_pressure")];
    char json_lookup_conf_mux_stringpool_str19[sizeof("resume_timeout")];
    char json_lookup_conf_mux_stringpool_str21[sizeof("max_streams")];
    char json_lookup_conf_mux_stringpool_str22[sizeof("max_halfopen")];
    char json_lookup_conf_mux_stringpool_str27[sizeof("ping_timeout")];
    char json_lookup_conf_mux_stringpool_str32[sizeof("idle_timeout")];
  };
static const struct json_lookup_conf_mux_stringpool_t json_lookup_conf_mux_stringpool_contents =
  {
    "tcp",
    "nodelay",
    "keepalive",
    "send_timeout",
    "stream_window",
    "session_window",
    "connect_timeout",
    "mem_pressure",
    "resume_timeout",
    "max_streams",
    "max_halfopen",
    "ping_timeout",
    "idle_timeout"
  };
#define json_lookup_conf_mux_stringpool ((const char *) &json_lookup_conf_mux_stringpool_contents)
static const struct json_lookup_conf_mux_kv *
json_lookup_conf_mux_kv_lookup_ (register const char *str, register size_t len)
{
  enum
    {
      TOTAL_KEYWORDS = 13,
      MIN_WORD_LENGTH = 3,
      MAX_WORD_LENGTH = 15,
      MIN_HASH_VALUE = 3,
      MAX_HASH_VALUE = 32
    };

  static const unsigned char lengthtable[] =
    {
       0,  0,  0,  3,  0,  0,  0,  7,  0,  9,  0,  0, 12, 13,
      14, 15,  0, 12,  0, 14,  0, 11, 12,  0,  0,  0,  0, 12,
       0,  0,  0,  0, 12
    };
  static const struct json_lookup_conf_mux_kv wordlist[] =
    {
      {-1,0}, {-1,0}, {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str3, 12},
      {-1,0}, {-1,0}, {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str7, 6},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str9, 2},
      {-1,0}, {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str12, 9},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str13, 11},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str14, 10},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str15, 0},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str17, 5},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str19, 8},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str21, 4},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str22, 3},
      {-1,0}, {-1,0}, {-1,0}, {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str27, 7},
      {-1,0}, {-1,0}, {-1,0}, {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_stringpool_t *)0)->json_lookup_conf_mux_stringpool_str32, 1}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = json_lookup_conf_mux_hash (str, len);

      if (key <= MAX_HASH_VALUE)
        if (len == lengthtable[key])
          {
            register const char *s = wordlist[key].name + json_lookup_conf_mux_stringpool;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &wordlist[key];
          }
    }
  return 0;
}


#ifdef TOTAL_KEYWORDS
#undef TOTAL_KEYWORDS
#endif
#ifdef MIN_WORD_LENGTH
#undef MIN_WORD_LENGTH
#endif
#ifdef MAX_WORD_LENGTH
#undef MAX_WORD_LENGTH
#endif
#ifdef MIN_HASH_VALUE
#undef MIN_HASH_VALUE
#endif
#ifdef MAX_HASH_VALUE
#undef MAX_HASH_VALUE
#endif

static int
json_lookup_conf_mux(const char *str, size_t len)
{
	const struct json_lookup_conf_mux_kv *kv_ = json_lookup_conf_mux_kv_lookup_(str, len);
	return kv_ ? kv_->idx : -1;
}

/* --- json_conf_mux_mem_pressure --- */
static int
json_lookup_conf_mux_mem_pressure(const char *str, size_t len)
{
	if (len < 1) { return -1; }
	switch ((unsigned char)str[0]) {
	case 'h':
		return len == 2 && memcmp(str, "hi", 2) == 0 ? 0 : -1;
	case 'l':
		return len == 2 && memcmp(str, "lo", 2) == 0 ? 1 : -1;
	default: return -1;
	}
}

/* --- json_conf_mux_tcp --- */
/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: gperf -l -c -E -P -Qjson_lookup_conf_mux_tcp_stringpool --null-strings --initializer-suffix=,0  */
/* Computed positions: -k'1' */



/* json_lookup_conf_mux_tcp: 7 keys  (auto-generated -- do not edit) */
struct json_lookup_conf_mux_tcp_kv { int name; int idx; };
/* maximum key range = 9, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
json_lookup_conf_mux_tcp_hash (register const char *str, register size_t len)
{
	(void)(str);
  static const unsigned char asso_values[] =
    {
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15,  5, 15,
      15, 15, 15, 15, 15, 15, 15,  5, 15, 15,
       0, 15, 15, 15,  0,  5, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15
    };
  return len + asso_values[(unsigned char)str[0]];
}

struct json_lookup_conf_mux_tcp_stringpool_t
  {
    char json_lookup_conf_mux_tcp_stringpool_str6[sizeof("rcvbuf")];
    char json_lookup_conf_mux_tcp_stringpool_str7[sizeof("nodelay")];
    char json_lookup_conf_mux_tcp_stringpool_str9[sizeof("reuseport")];
    char json_lookup_conf_mux_tcp_stringpool_str11[sizeof("sndbuf")];
    char json_lookup_conf_mux_tcp_stringpool_str12[sizeof("backlog")];
    char json_lookup_conf_mux_tcp_stringpool_str13[sizeof("notsent_lowat")];
    char json_lookup_conf_mux_tcp_stringpool_str14[sizeof("keepalive")];
  };
static const struct json_lookup_conf_mux_tcp_stringpool_t json_lookup_conf_mux_tcp_stringpool_contents =
  {
    "rcvbuf",
    "nodelay",
    "reuseport",
    "sndbuf",
    "backlog",
    "notsent_lowat",
    "keepalive"
  };
#define json_lookup_conf_mux_tcp_stringpool ((const char *) &json_lookup_conf_mux_tcp_stringpool_contents)
static const struct json_lookup_conf_mux_tcp_kv *
json_lookup_conf_mux_tcp_kv_lookup_ (register const char *str, register size_t len)
{
  enum
    {
      TOTAL_KEYWORDS = 7,
      MIN_WORD_LENGTH = 6,
      MAX_WORD_LENGTH = 13,
      MIN_HASH_VALUE = 6,
      MAX_HASH_VALUE = 14
    };

  static const unsigned char lengthtable[] =
    {
       0,  0,  0,  0,  0,  0,  6,  7,  0,  9,  0,  6,  7, 13,
       9
    };
  static const struct json_lookup_conf_mux_tcp_kv wordlist[] =
    {
      {-1,0}, {-1,0}, {-1,0}, {-1,0}, {-1,0}, {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_tcp_stringpool_t *)0)->json_lookup_conf_mux_tcp_stringpool_str6, 4},
      {(int)(size_t)&((struct json_lookup_conf_mux_tcp_stringpool_t *)0)->json_lookup_conf_mux_tcp_stringpool_str7, 2},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_tcp_stringpool_t *)0)->json_lookup_conf_mux_tcp_stringpool_str9, 5},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_mux_tcp_stringpool_t *)0)->json_lookup_conf_mux_tcp_stringpool_str11, 6},
      {(int)(size_t)&((struct json_lookup_conf_mux_tcp_stringpool_t *)0)->json_lookup_conf_mux_tcp_stringpool_str12, 0},
      {(int)(size_t)&((struct json_lookup_conf_mux_tcp_stringpool_t *)0)->json_lookup_conf_mux_tcp_stringpool_str13, 3},
      {(int)(size_t)&((struct json_lookup_conf_mux_tcp_stringpool_t *)0)->json_lookup_conf_mux_tcp_stringpool_str14, 1}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = json_lookup_conf_mux_tcp_hash (str, len);

      if (key <= MAX_HASH_VALUE)
        if (len == lengthtable[key])
          {
            register const char *s = wordlist[key].name + json_lookup_conf_mux_tcp_stringpool;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &wordlist[key];
          }
    }
  return 0;
}


#ifdef TOTAL_KEYWORDS
#undef TOTAL_KEYWORDS
#endif
#ifdef MIN_WORD_LENGTH
#undef MIN_WORD_LENGTH
#endif
#ifdef MAX_WORD_LENGTH
#undef MAX_WORD_LENGTH
#endif
#ifdef MIN_HASH_VALUE
#undef MIN_HASH_VALUE
#endif
#ifdef MAX_HASH_VALUE
#undef MAX_HASH_VALUE
#endif

static int
json_lookup_conf_mux_tcp(const char *str, size_t len)
{
	const struct json_lookup_conf_mux_tcp_kv *kv_ = json_lookup_conf_mux_tcp_kv_lookup_(str, len);
	return kv_ ? kv_->idx : -1;
}

/* --- json_conf_tcp --- */
/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: gperf -l -c -E -P -Qjson_lookup_conf_tcp_stringpool --null-strings --initializer-suffix=,0  */
/* Computed positions: -k'1' */



/* json_lookup_conf_tcp: 7 keys  (auto-generated -- do not edit) */
struct json_lookup_conf_tcp_kv { int name; int idx; };
/* maximum key range = 9, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
json_lookup_conf_tcp_hash (register const char *str, register size_t len)
{
	(void)(str);
  static const unsigned char asso_values[] =
    {
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15,  5, 15,
      15, 15, 15, 15, 15, 15, 15,  5, 15, 15,
       0, 15, 15, 15,  0,  5, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15
    };
  return len + asso_values[(unsigned char)str[0]];
}

struct json_lookup_conf_tcp_stringpool_t
  {
    char json_lookup_conf_tcp_stringpool_str6[sizeof("rcvbuf")];
    char json_lookup_conf_tcp_stringpool_str7[sizeof("nodelay")];
    char json_lookup_conf_tcp_stringpool_str9[sizeof("reuseport")];
    char json_lookup_conf_tcp_stringpool_str11[sizeof("sndbuf")];
    char json_lookup_conf_tcp_stringpool_str12[sizeof("backlog")];
    char json_lookup_conf_tcp_stringpool_str13[sizeof("notsent_lowat")];
    char json_lookup_conf_tcp_stringpool_str14[sizeof("keepalive")];
  };
static const struct json_lookup_conf_tcp_stringpool_t json_lookup_conf_tcp_stringpool_contents =
  {
    "rcvbuf",
    "nodelay",
    "reuseport",
    "sndbuf",
    "backlog",
    "notsent_lowat",
    "keepalive"
  };
#define json_lookup_conf_tcp_stringpool ((const char *) &json_lookup_conf_tcp_stringpool_contents)
static const struct json_lookup_conf_tcp_kv *
json_lookup_conf_tcp_kv_lookup_ (register const char *str, register size_t len)
{
  enum
    {
      TOTAL_KEYWORDS = 7,
      MIN_WORD_LENGTH = 6,
      MAX_WORD_LENGTH = 13,
      MIN_HASH_VALUE = 6,
      MAX_HASH_VALUE = 14
    };

  static const unsigned char lengthtable[] =
    {
       0,  0,  0,  0,  0,  0,  6,  7,  0,  9,  0,  6,  7, 13,
       9
    };
  static const struct json_lookup_conf_tcp_kv wordlist[] =
    {
      {-1,0}, {-1,0}, {-1,0}, {-1,0}, {-1,0}, {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_tcp_stringpool_t *)0)->json_lookup_conf_tcp_stringpool_str6, 4},
      {(int)(size_t)&((struct json_lookup_conf_tcp_stringpool_t *)0)->json_lookup_conf_tcp_stringpool_str7, 2},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_tcp_stringpool_t *)0)->json_lookup_conf_tcp_stringpool_str9, 5},
      {-1,0},
      {(int)(size_t)&((struct json_lookup_conf_tcp_stringpool_t *)0)->json_lookup_conf_tcp_stringpool_str11, 6},
      {(int)(size_t)&((struct json_lookup_conf_tcp_stringpool_t *)0)->json_lookup_conf_tcp_stringpool_str12, 0},
      {(int)(size_t)&((struct json_lookup_conf_tcp_stringpool_t *)0)->json_lookup_conf_tcp_stringpool_str13, 3},
      {(int)(size_t)&((struct json_lookup_conf_tcp_stringpool_t *)0)->json_lookup_conf_tcp_stringpool_str14, 1}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = json_lookup_conf_tcp_hash (str, len);

      if (key <= MAX_HASH_VALUE)
        if (len == lengthtable[key])
          {
            register const char *s = wordlist[key].name + json_lookup_conf_tcp_stringpool;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &wordlist[key];
          }
    }
  return 0;
}


#ifdef TOTAL_KEYWORDS
#undef TOTAL_KEYWORDS
#endif
#ifdef MIN_WORD_LENGTH
#undef MIN_WORD_LENGTH
#endif
#ifdef MAX_WORD_LENGTH
#undef MAX_WORD_LENGTH
#endif
#ifdef MIN_HASH_VALUE
#undef MIN_HASH_VALUE
#endif
#ifdef MAX_HASH_VALUE
#undef MAX_HASH_VALUE
#endif

static int
json_lookup_conf_tcp(const char *str, size_t len)
{
	const struct json_lookup_conf_tcp_kv *kv_ = json_lookup_conf_tcp_kv_lookup_(str, len);
	return kv_ ? kv_->idx : -1;
}

/* --- json_conf_tls --- */
static int
json_lookup_conf_tls(const char *str, size_t len)
{
	if (len < 3) { return -1; }
	switch ((unsigned char)str[2]) {
	case 't':
		return len == 9 && memcmp(str, "authcerts", 9) == 0 ? 0 : -1;
	case 'r':
		return len == 4 && memcmp(str, "cert", 4) == 0 ? 1 : -1;
	case 'p':
		return len == 12 && memcmp(str, "ciphersuites", 12) == 0 ? 2 : -1;
	case 'y':
		return len == 3 && memcmp(str, "key", 3) == 0 ? 3 : -1;
	default: return -1;
	}
}

/** @} */

/** @name Key indices
 *  @{ */

enum json_conf_key {
	JSON_CONF_API_LISTEN = 0,
	JSON_CONF_CONNECT = 1,
	JSON_CONF_IDENTITY = 2,
	JSON_CONF_LISTEN = 3,
	JSON_CONF_LOGLEVEL = 4,
	JSON_CONF_MAX_SESSIONS = 5,
	JSON_CONF_MAX_STARTUPS = 6,
	JSON_CONF_MUX = 7,
	JSON_CONF_MUX_CONNECT = 8,
	JSON_CONF_MUX_LISTEN = 9,
	JSON_CONF_TCP = 10,
	JSON_CONF_TLS = 11,
	JSON_CONF_TYPE = 12,
};

enum json_conf_identity_key {
	JSON_CONF_IDENTITY_AUTHCERTS = 0,
	JSON_CONF_IDENTITY_CLAIM = 1,
	JSON_CONF_IDENTITY_LISTEN = 2,
	JSON_CONF_IDENTITY_MUX_CONNECT = 3,
};

enum json_conf_mux_key {
	JSON_CONF_MUX_CONNECT_TIMEOUT = 0,
	JSON_CONF_MUX_IDLE_TIMEOUT = 1,
	JSON_CONF_MUX_KEEPALIVE = 2,
	JSON_CONF_MUX_MAX_HALFOPEN = 3,
	JSON_CONF_MUX_MAX_STREAMS = 4,
	JSON_CONF_MUX_MEM_PRESSURE = 5,
	JSON_CONF_MUX_NODELAY = 6,
	JSON_CONF_MUX_PING_TIMEOUT = 7,
	JSON_CONF_MUX_RESUME_TIMEOUT = 8,
	JSON_CONF_MUX_SEND_TIMEOUT = 9,
	JSON_CONF_MUX_SESSION_WINDOW = 10,
	JSON_CONF_MUX_STREAM_WINDOW = 11,
	JSON_CONF_MUX_TCP = 12,
};

enum json_conf_mux_mem_pressure_key {
	JSON_CONF_MUX_MEM_PRESSURE_HI = 0,
	JSON_CONF_MUX_MEM_PRESSURE_LO = 1,
};

enum json_conf_mux_tcp_key {
	JSON_CONF_MUX_TCP_BACKLOG = 0,
	JSON_CONF_MUX_TCP_KEEPALIVE = 1,
	JSON_CONF_MUX_TCP_NODELAY = 2,
	JSON_CONF_MUX_TCP_NOTSENT_LOWAT = 3,
	JSON_CONF_MUX_TCP_RCVBUF = 4,
	JSON_CONF_MUX_TCP_REUSEPORT = 5,
	JSON_CONF_MUX_TCP_SNDBUF = 6,
};

enum json_conf_tcp_key {
	JSON_CONF_TCP_BACKLOG = 0,
	JSON_CONF_TCP_KEEPALIVE = 1,
	JSON_CONF_TCP_NODELAY = 2,
	JSON_CONF_TCP_NOTSENT_LOWAT = 3,
	JSON_CONF_TCP_RCVBUF = 4,
	JSON_CONF_TCP_REUSEPORT = 5,
	JSON_CONF_TCP_SNDBUF = 6,
};

enum json_conf_tls_key {
	JSON_CONF_TLS_AUTHCERTS = 0,
	JSON_CONF_TLS_CERT = 1,
	JSON_CONF_TLS_CIPHERSUITES = 2,
	JSON_CONF_TLS_KEY = 3,
};

/** @} */

/** @name Free
 *  @{ */

static void json_free_conf_tls(struct json_conf_tls *obj)
{
	free(obj->authcerts);
}

static void json_free_conf_tcp(struct json_conf_tcp *obj)
{
	(void)obj;
}

static void json_free_conf_mux_tcp(struct json_conf_mux_tcp *obj)
{
	(void)obj;
}

static void json_free_conf_mux_mem_pressure(struct json_conf_mux_mem_pressure *obj)
{
	(void)obj;
}

static void json_free_conf_mux(struct json_conf_mux *obj)
{
	json_free_conf_mux_mem_pressure(&obj->mem_pressure);
	json_free_conf_mux_tcp(&obj->tcp);
}

static void json_free_conf_identity(struct json_conf_identity *obj)
{
	free(obj->mux_connect);
}

void json_free_conf(struct json_conf *obj)
{
	json_free_conf_identity(&obj->identity);
	json_free_conf_mux(&obj->mux);
	json_free_conf_tcp(&obj->tcp);
	json_free_conf_tls(&obj->tls);
}

/** @} */

/** @name Unmarshal
 *  @{ */

static bool json_unmarshal_conf_tls_arr_authcerts(
	struct json_conf_tls *obj, char *val_, size_t val_len_)
{
	const struct json_val arr_ = json_parse(val_, &(size_t){ val_len_ });
	if (arr_.type != JSON_ARRAY) { return false; }
	struct json_string *items_ = NULL;
	size_t count_ = 0, cap_ = 0;
	json_iter ait_ = arr_.iter;
	char *av_; size_t alen_;
	while (json_arr_next(val_, &val_len_, &ait_, &av_, &alen_)) {
		if (count_ >= cap_) {
			const size_t nc_ = cap_ ? cap_ * 2 : 4;
			struct json_string *na_ = realloc(items_, nc_ * sizeof(*na_));
			if (na_ == NULL) {
				free(items_);
				return false;
			}
			items_ = na_; cap_ = nc_;
		}
		if (!json_parse_string(av_, alen_, &items_[count_].str, &items_[count_].len)) {
			free(items_);
			return false;
		}
		count_++;
	}
	for (; ait_ < val_len_; ait_++) {
		if (!json_iswhitespace(val_[ait_])) { free(items_); return false; }
	}
	obj->authcerts = items_;
	obj->authcerts_count = count_;
	return true;
}

static bool json_unmarshal_conf_tls(
	struct json_conf_tls *obj, char *json, size_t length)
{
	const struct json_val root_ = json_parse(json, &(size_t){ length });
	if (root_.type != JSON_OBJECT) { return false; }
	json_iter iter_ = root_.iter;
	char *key_; size_t key_len_; char *val_; size_t val_len_;
	*obj = (struct json_conf_tls){ 0 };

	while (json_obj_next(json, &length, &iter_,
			&key_, &key_len_, &val_, &val_len_)) {
		const int k_ = json_lookup_conf_tls(key_, key_len_);
		switch (k_) {
		case JSON_CONF_TLS_AUTHCERTS: {
			if (!json_unmarshal_conf_tls_arr_authcerts(obj, val_, val_len_)) { return false; }
			if (obj->authcerts_count < 1u) { return false; }
			break;
		}
		case JSON_CONF_TLS_CERT: {
			if (!json_parse_string(val_, val_len_, &obj->cert.str, &obj->cert.len)) { return false; }
			break;
		}
		case JSON_CONF_TLS_CIPHERSUITES: {
			if (!json_parse_string(val_, val_len_, &obj->ciphersuites.str, &obj->ciphersuites.len)) { return false; }
			break;
		}
		case JSON_CONF_TLS_KEY: {
			if (!json_parse_string(val_, val_len_, &obj->key.str, &obj->key.len)) { return false; }
			break;
		}
		default:
			break;
		}
	}
	for (; iter_ < length; iter_++) {
		if (!json_iswhitespace(json[iter_])) { return false; }
	}
	return true;
}

static bool json_unmarshal_conf_tcp(
	struct json_conf_tcp *obj, char *json, size_t length)
{
	const struct json_val root_ = json_parse(json, &(size_t){ length });
	if (root_.type != JSON_OBJECT) { return false; }
	json_iter iter_ = root_.iter;
	char *key_; size_t key_len_; char *val_; size_t val_len_;
	*obj = (struct json_conf_tcp){
		.backlog = 16u,
		.keepalive = true,
		.nodelay = true,
		.notsent_lowat = UINTMAX_C(0),
		.reuseport = false,
	};

	while (json_obj_next(json, &length, &iter_,
			&key_, &key_len_, &val_, &val_len_)) {
		const int k_ = json_lookup_conf_tcp(key_, key_len_);
		switch (k_) {
		case JSON_CONF_TCP_BACKLOG: {
			if (!json_parse_uint(val_, val_len_, &obj->backlog)) { return false; }
			if (obj->backlog < 1u) { return false; }
			if (obj->backlog > 4096u) { return false; }
			break;
		}
		case JSON_CONF_TCP_KEEPALIVE: {
			if (!json_parse_bool(val_, val_len_, &obj->keepalive)) { return false; }
			break;
		}
		case JSON_CONF_TCP_NODELAY: {
			if (!json_parse_bool(val_, val_len_, &obj->nodelay)) { return false; }
			break;
		}
		case JSON_CONF_TCP_NOTSENT_LOWAT: {
			if (!json_parse_umax(val_, val_len_, &obj->notsent_lowat)) { return false; }
			break;
		}
		case JSON_CONF_TCP_RCVBUF: {
			if (!json_parse_umax(val_, val_len_, &obj->rcvbuf)) { return false; }
			break;
		}
		case JSON_CONF_TCP_REUSEPORT: {
			if (!json_parse_bool(val_, val_len_, &obj->reuseport)) { return false; }
			break;
		}
		case JSON_CONF_TCP_SNDBUF: {
			if (!json_parse_umax(val_, val_len_, &obj->sndbuf)) { return false; }
			break;
		}
		default:
			break;
		}
	}
	for (; iter_ < length; iter_++) {
		if (!json_iswhitespace(json[iter_])) { return false; }
	}
	return true;
}

static bool json_unmarshal_conf_mux_tcp(
	struct json_conf_mux_tcp *obj, char *json, size_t length)
{
	const struct json_val root_ = json_parse(json, &(size_t){ length });
	if (root_.type != JSON_OBJECT) { return false; }
	json_iter iter_ = root_.iter;
	char *key_; size_t key_len_; char *val_; size_t val_len_;
	*obj = (struct json_conf_mux_tcp){
		.backlog = 16u,
		.keepalive = false,
		.nodelay = true,
		.notsent_lowat = UINTMAX_C(131072),
		.reuseport = false,
	};

	while (json_obj_next(json, &length, &iter_,
			&key_, &key_len_, &val_, &val_len_)) {
		const int k_ = json_lookup_conf_mux_tcp(key_, key_len_);
		switch (k_) {
		case JSON_CONF_MUX_TCP_BACKLOG: {
			if (!json_parse_uint(val_, val_len_, &obj->backlog)) { return false; }
			if (obj->backlog < 1u) { return false; }
			if (obj->backlog > 4096u) { return false; }
			break;
		}
		case JSON_CONF_MUX_TCP_KEEPALIVE: {
			if (!json_parse_bool(val_, val_len_, &obj->keepalive)) { return false; }
			break;
		}
		case JSON_CONF_MUX_TCP_NODELAY: {
			if (!json_parse_bool(val_, val_len_, &obj->nodelay)) { return false; }
			break;
		}
		case JSON_CONF_MUX_TCP_NOTSENT_LOWAT: {
			if (!json_parse_umax(val_, val_len_, &obj->notsent_lowat)) { return false; }
			break;
		}
		case JSON_CONF_MUX_TCP_RCVBUF: {
			if (!json_parse_umax(val_, val_len_, &obj->rcvbuf)) { return false; }
			break;
		}
		case JSON_CONF_MUX_TCP_REUSEPORT: {
			if (!json_parse_bool(val_, val_len_, &obj->reuseport)) { return false; }
			break;
		}
		case JSON_CONF_MUX_TCP_SNDBUF: {
			if (!json_parse_umax(val_, val_len_, &obj->sndbuf)) { return false; }
			break;
		}
		default:
			break;
		}
	}
	for (; iter_ < length; iter_++) {
		if (!json_iswhitespace(json[iter_])) { return false; }
	}
	return true;
}

static bool json_unmarshal_conf_mux_mem_pressure(
	struct json_conf_mux_mem_pressure *obj, char *json, size_t length)
{
	const struct json_val root_ = json_parse(json, &(size_t){ length });
	if (root_.type != JSON_OBJECT) { return false; }
	json_iter iter_ = root_.iter;
	char *key_; size_t key_len_; char *val_; size_t val_len_;
	*obj = (struct json_conf_mux_mem_pressure){
		.hi = UINTMAX_C(0),
		.lo = UINTMAX_C(0),
	};

	while (json_obj_next(json, &length, &iter_,
			&key_, &key_len_, &val_, &val_len_)) {
		const int k_ = json_lookup_conf_mux_mem_pressure(key_, key_len_);
		switch (k_) {
		case JSON_CONF_MUX_MEM_PRESSURE_HI: {
			if (!json_parse_umax(val_, val_len_, &obj->hi)) { return false; }
			break;
		}
		case JSON_CONF_MUX_MEM_PRESSURE_LO: {
			if (!json_parse_umax(val_, val_len_, &obj->lo)) { return false; }
			break;
		}
		default:
			break;
		}
	}
	for (; iter_ < length; iter_++) {
		if (!json_iswhitespace(json[iter_])) { return false; }
	}
	return true;
}

static bool json_unmarshal_conf_mux(
	struct json_conf_mux *obj, char *json, size_t length)
{
	const struct json_val root_ = json_parse(json, &(size_t){ length });
	if (root_.type != JSON_OBJECT) { return false; }
	json_iter iter_ = root_.iter;
	char *key_; size_t key_len_; char *val_; size_t val_len_;
	*obj = (struct json_conf_mux){
		.connect_timeout = 15u,
		.idle_timeout = 0u,
		.keepalive = 300u,
		.max_halfopen = 256u,
		.mem_pressure = {
			.hi = UINTMAX_C(0),
			.lo = UINTMAX_C(0),
		},
		.nodelay = true,
		.ping_timeout = 15u,
		.resume_timeout = 600u,
		.send_timeout = 15u,
		.session_window = 0u,
		.stream_window = 0u,
		.tcp = {
			.backlog = 16u,
			.keepalive = false,
			.nodelay = true,
			.notsent_lowat = UINTMAX_C(131072),
			.reuseport = false,
		},
	};

	while (json_obj_next(json, &length, &iter_,
			&key_, &key_len_, &val_, &val_len_)) {
		const int k_ = json_lookup_conf_mux(key_, key_len_);
		switch (k_) {
		case JSON_CONF_MUX_CONNECT_TIMEOUT: {
			if (!json_parse_uint(val_, val_len_, &obj->connect_timeout)) { return false; }
			if (obj->connect_timeout > 86400u) { return false; }
			break;
		}
		case JSON_CONF_MUX_IDLE_TIMEOUT: {
			if (!json_parse_uint(val_, val_len_, &obj->idle_timeout)) { return false; }
			if (obj->idle_timeout > 86400u) { return false; }
			break;
		}
		case JSON_CONF_MUX_KEEPALIVE: {
			if (!json_parse_uint(val_, val_len_, &obj->keepalive)) { return false; }
			if (obj->keepalive > 86400u) { return false; }
			break;
		}
		case JSON_CONF_MUX_MAX_HALFOPEN: {
			if (!json_parse_uint(val_, val_len_, &obj->max_halfopen)) { return false; }
			if (obj->max_halfopen > 4096u) { return false; }
			break;
		}
		case JSON_CONF_MUX_MAX_STREAMS: {
			if (!json_parse_umax(val_, val_len_, &obj->max_streams)) { return false; }
			break;
		}
		case JSON_CONF_MUX_MEM_PRESSURE: {
			if (!json_unmarshal_conf_mux_mem_pressure(&obj->mem_pressure, val_, val_len_)) {
				return false;
			}
			break;
		}
		case JSON_CONF_MUX_NODELAY: {
			if (!json_parse_bool(val_, val_len_, &obj->nodelay)) { return false; }
			break;
		}
		case JSON_CONF_MUX_PING_TIMEOUT: {
			if (!json_parse_uint(val_, val_len_, &obj->ping_timeout)) { return false; }
			if (obj->ping_timeout > 86400u) { return false; }
			break;
		}
		case JSON_CONF_MUX_RESUME_TIMEOUT: {
			if (!json_parse_uint(val_, val_len_, &obj->resume_timeout)) { return false; }
			if (obj->resume_timeout > 86400u) { return false; }
			break;
		}
		case JSON_CONF_MUX_SEND_TIMEOUT: {
			if (!json_parse_uint(val_, val_len_, &obj->send_timeout)) { return false; }
			if (obj->send_timeout > 86400u) { return false; }
			break;
		}
		case JSON_CONF_MUX_SESSION_WINDOW: {
			if (!json_parse_uint(val_, val_len_, &obj->session_window)) { return false; }
			if (obj->session_window > 1073725440u) { return false; }
			break;
		}
		case JSON_CONF_MUX_STREAM_WINDOW: {
			if (!json_parse_uint(val_, val_len_, &obj->stream_window)) { return false; }
			if (obj->stream_window > 1073725440u) { return false; }
			break;
		}
		case JSON_CONF_MUX_TCP: {
			if (!json_unmarshal_conf_mux_tcp(&obj->tcp, val_, val_len_)) {
				return false;
			}
			break;
		}
		default:
			break;
		}
	}
	for (; iter_ < length; iter_++) {
		if (!json_iswhitespace(json[iter_])) { return false; }
	}
	return true;
}

static bool json_unmarshal_conf_identity_arr_mux_connect(
	struct json_conf_identity *obj, char *val_, size_t val_len_)
{
	const struct json_val arr_ = json_parse(val_, &(size_t){ val_len_ });
	if (arr_.type != JSON_ARRAY) { return false; }
	struct json_string *items_ = NULL;
	size_t count_ = 0, cap_ = 0;
	json_iter ait_ = arr_.iter;
	char *av_; size_t alen_;
	while (json_arr_next(val_, &val_len_, &ait_, &av_, &alen_)) {
		if (count_ >= cap_) {
			const size_t nc_ = cap_ ? cap_ * 2 : 4;
			struct json_string *na_ = realloc(items_, nc_ * sizeof(*na_));
			if (na_ == NULL) {
				free(items_);
				return false;
			}
			items_ = na_; cap_ = nc_;
		}
		if (!json_parse_string(av_, alen_, &items_[count_].str, &items_[count_].len)) {
			free(items_);
			return false;
		}
		count_++;
	}
	for (; ait_ < val_len_; ait_++) {
		if (!json_iswhitespace(val_[ait_])) { free(items_); return false; }
	}
	obj->mux_connect = items_;
	obj->mux_connect_count = count_;
	return true;
}

static bool json_unmarshal_conf_identity(
	struct json_conf_identity *obj, char *json, size_t length)
{
	const struct json_val root_ = json_parse(json, &(size_t){ length });
	if (root_.type != JSON_OBJECT) { return false; }
	json_iter iter_ = root_.iter;
	char *key_; size_t key_len_; char *val_; size_t val_len_;
	*obj = (struct json_conf_identity){ 0 };

	while (json_obj_next(json, &length, &iter_,
			&key_, &key_len_, &val_, &val_len_)) {
		const int k_ = json_lookup_conf_identity(key_, key_len_);
		switch (k_) {
		case JSON_CONF_IDENTITY_AUTHCERTS: {
			obj->authcerts_json.str = val_;
			obj->authcerts_json.len = val_len_;
			break;
		}
		case JSON_CONF_IDENTITY_CLAIM: {
			if (!json_parse_string(val_, val_len_, &obj->claim.str, &obj->claim.len)) { return false; }
			break;
		}
		case JSON_CONF_IDENTITY_LISTEN: {
			obj->listen_json.str = val_;
			obj->listen_json.len = val_len_;
			break;
		}
		case JSON_CONF_IDENTITY_MUX_CONNECT: {
			if (!json_unmarshal_conf_identity_arr_mux_connect(obj, val_, val_len_)) { return false; }
			break;
		}
		default:
			break;
		}
	}
	for (; iter_ < length; iter_++) {
		if (!json_iswhitespace(json[iter_])) { return false; }
	}
	return true;
}

bool json_unmarshal_conf(
	struct json_conf *obj, char *json, size_t length)
{
	const struct json_val root_ = json_parse(json, &(size_t){ length });
	if (root_.type != JSON_OBJECT) { return false; }
	json_iter iter_ = root_.iter;
	char *key_; size_t key_len_; char *val_; size_t val_len_;
	*obj = (struct json_conf){
		.loglevel = UINTMAX_C(4),
		.mux = {
			.connect_timeout = 15u,
			.idle_timeout = 0u,
			.keepalive = 300u,
			.max_halfopen = 256u,
			.mem_pressure = {
				.hi = UINTMAX_C(0),
				.lo = UINTMAX_C(0),
			},
			.nodelay = true,
			.ping_timeout = 15u,
			.resume_timeout = 600u,
			.send_timeout = 15u,
			.session_window = 0u,
			.stream_window = 0u,
			.tcp = {
				.backlog = 16u,
				.keepalive = false,
				.nodelay = true,
				.notsent_lowat = UINTMAX_C(131072),
				.reuseport = false,
			},
		},
		.tcp = {
			.backlog = 16u,
			.keepalive = true,
			.nodelay = true,
			.notsent_lowat = UINTMAX_C(0),
			.reuseport = false,
		},
	};

	while (json_obj_next(json, &length, &iter_,
			&key_, &key_len_, &val_, &val_len_)) {
		const int k_ = json_lookup_conf(key_, key_len_);
		switch (k_) {
		case JSON_CONF_API_LISTEN: {
			if (!json_parse_string(val_, val_len_, &obj->api_listen.str, &obj->api_listen.len)) { return false; }
			break;
		}
		case JSON_CONF_CONNECT: {
			if (!json_parse_string(val_, val_len_, &obj->connect.str, &obj->connect.len)) { return false; }
			break;
		}
		case JSON_CONF_IDENTITY: {
			if (!json_unmarshal_conf_identity(&obj->identity, val_, val_len_)) {
				return false;
			}
			break;
		}
		case JSON_CONF_LISTEN: {
			if (!json_parse_string(val_, val_len_, &obj->listen.str, &obj->listen.len)) { return false; }
			break;
		}
		case JSON_CONF_LOGLEVEL: {
			if (!json_parse_umax(val_, val_len_, &obj->loglevel)) { return false; }
			break;
		}
		case JSON_CONF_MAX_SESSIONS: {
			if (!json_parse_umax(val_, val_len_, &obj->max_sessions)) { return false; }
			break;
		}
		case JSON_CONF_MAX_STARTUPS: {
			if (!json_parse_string(val_, val_len_, &obj->max_startups.str, &obj->max_startups.len)) { return false; }
			break;
		}
		case JSON_CONF_MUX: {
			if (!json_unmarshal_conf_mux(&obj->mux, val_, val_len_)) {
				return false;
			}
			break;
		}
		case JSON_CONF_MUX_CONNECT: {
			if (!json_parse_string(val_, val_len_, &obj->mux_connect.str, &obj->mux_connect.len)) { return false; }
			break;
		}
		case JSON_CONF_MUX_LISTEN: {
			if (!json_parse_string(val_, val_len_, &obj->mux_listen.str, &obj->mux_listen.len)) { return false; }
			break;
		}
		case JSON_CONF_TCP: {
			if (!json_unmarshal_conf_tcp(&obj->tcp, val_, val_len_)) {
				return false;
			}
			break;
		}
		case JSON_CONF_TLS: {
			if (!json_unmarshal_conf_tls(&obj->tls, val_, val_len_)) {
				return false;
			}
			break;
		}
		case JSON_CONF_TYPE: {
			if (!json_parse_string(val_, val_len_, &obj->type.str, &obj->type.len)) { return false; }
			if (!(obj->type.len == 42u && memcmp(obj->type.str, "application/x-multiplexd-config; version=1", 42) == 0)) { return false; }
			break;
		}
		default:
			break;
		}
	}
	for (; iter_ < length; iter_++) {
		if (!json_iswhitespace(json[iter_])) { return false; }
	}
	return true;
}

/** @} */

/** @name Marshal
 *  @{ */

#define EMIT(fmt, ...) do { \
	r_ = snprintf(buf ? buf + n_ : NULL, \
		bufsz > (size_t)n_ ? bufsz - (size_t)n_ : 0, fmt, __VA_ARGS__); \
	if (r_ < 0) { return -1; } \
	n_ += r_; \
} while (0)
#define EMIT_STR(s, len) do { \
	r_ = json_marshal_string(buf ? buf + n_ : NULL, \
		bufsz > (size_t)n_ ? bufsz - (size_t)n_ : 0, (s), (len)); \
	if (r_ < 0) { return -1; } \
	n_ += r_; \
} while (0)
#define EMIT_SUB(fn, arg) do { \
	r_ = (fn)(buf ? buf + n_ : NULL, \
		bufsz > (size_t)n_ ? bufsz - (size_t)n_ : 0, (arg)); \
	if (r_ < 0) { return -1; } \
	n_ += r_; \
} while (0)
#define EMIT_LIT(s) do { \
	static const char lit_[] = s; \
	const int l_ = (int)(sizeof(lit_) - 1); \
	if (buf && bufsz > (size_t)n_ + (size_t)l_) \
		memcpy(buf + n_, lit_, (size_t)l_); \
	n_ += l_; \
} while (0)

static int json_marshal_conf_tls(
	char *buf, size_t bufsz, const struct json_conf_tls *obj)
{
	int n_ = 0;
	int r_;

	EMIT_LIT("{");
	const int n_start_ = n_;

	if (obj->authcerts != NULL) {
		EMIT_LIT("\"authcerts\":[");
		for (size_t i_ = 0; i_ < obj->authcerts_count; i_++) {
			if (i_ > 0) { if (buf && bufsz > (size_t)n_) buf[n_] = ','; n_++; }
			EMIT_STR(obj->authcerts[i_].str, obj->authcerts[i_].len);
		}
		EMIT_LIT("],");
	}
	if (obj->cert.str != NULL) {
		EMIT_LIT("\"cert\":");
		EMIT_STR(obj->cert.str, obj->cert.len);
		EMIT_LIT(",");
	}
	if (obj->ciphersuites.str != NULL) {
		EMIT_LIT("\"ciphersuites\":");
		EMIT_STR(obj->ciphersuites.str, obj->ciphersuites.len);
		EMIT_LIT(",");
	}
	if (obj->key.str != NULL) {
		EMIT_LIT("\"key\":");
		EMIT_STR(obj->key.str, obj->key.len);
		EMIT_LIT(",");
	}

	if (n_ > n_start_) { n_--; }
	EMIT_LIT("}");

	return n_;
}

static int json_marshal_conf_tcp(
	char *buf, size_t bufsz, const struct json_conf_tcp *obj)
{
	int n_ = 0;
	int r_;

	EMIT_LIT("{");
	const int n_start_ = n_;

	EMIT("\"%s\":%ju,", "backlog",
		(uintmax_t)obj->backlog);
	EMIT_LIT("\"keepalive\":");
	if (obj->keepalive) {
		EMIT_LIT("true,");
	} else {
		EMIT_LIT("false,");
	}
	EMIT_LIT("\"nodelay\":");
	if (obj->nodelay) {
		EMIT_LIT("true,");
	} else {
		EMIT_LIT("false,");
	}
	EMIT("\"%s\":%ju,", "notsent_lowat",
		(uintmax_t)obj->notsent_lowat);
	EMIT("\"%s\":%ju,", "rcvbuf",
		(uintmax_t)obj->rcvbuf);
	EMIT_LIT("\"reuseport\":");
	if (obj->reuseport) {
		EMIT_LIT("true,");
	} else {
		EMIT_LIT("false,");
	}
	EMIT("\"%s\":%ju,", "sndbuf",
		(uintmax_t)obj->sndbuf);

	if (n_ > n_start_) { n_--; }
	EMIT_LIT("}");

	return n_;
}

static int json_marshal_conf_mux_tcp(
	char *buf, size_t bufsz, const struct json_conf_mux_tcp *obj)
{
	int n_ = 0;
	int r_;

	EMIT_LIT("{");
	const int n_start_ = n_;

	EMIT("\"%s\":%ju,", "backlog",
		(uintmax_t)obj->backlog);
	EMIT_LIT("\"keepalive\":");
	if (obj->keepalive) {
		EMIT_LIT("true,");
	} else {
		EMIT_LIT("false,");
	}
	EMIT_LIT("\"nodelay\":");
	if (obj->nodelay) {
		EMIT_LIT("true,");
	} else {
		EMIT_LIT("false,");
	}
	EMIT("\"%s\":%ju,", "notsent_lowat",
		(uintmax_t)obj->notsent_lowat);
	EMIT("\"%s\":%ju,", "rcvbuf",
		(uintmax_t)obj->rcvbuf);
	EMIT_LIT("\"reuseport\":");
	if (obj->reuseport) {
		EMIT_LIT("true,");
	} else {
		EMIT_LIT("false,");
	}
	EMIT("\"%s\":%ju,", "sndbuf",
		(uintmax_t)obj->sndbuf);

	if (n_ > n_start_) { n_--; }
	EMIT_LIT("}");

	return n_;
}

static int json_marshal_conf_mux_mem_pressure(
	char *buf, size_t bufsz, const struct json_conf_mux_mem_pressure *obj)
{
	int n_ = 0;
	int r_;

	EMIT_LIT("{");
	const int n_start_ = n_;

	EMIT("\"%s\":%ju,", "hi",
		(uintmax_t)obj->hi);
	EMIT("\"%s\":%ju,", "lo",
		(uintmax_t)obj->lo);

	if (n_ > n_start_) { n_--; }
	EMIT_LIT("}");

	return n_;
}

static int json_marshal_conf_mux(
	char *buf, size_t bufsz, const struct json_conf_mux *obj)
{
	int n_ = 0;
	int r_;

	EMIT_LIT("{");
	const int n_start_ = n_;

	EMIT("\"%s\":%ju,", "connect_timeout",
		(uintmax_t)obj->connect_timeout);
	EMIT("\"%s\":%ju,", "idle_timeout",
		(uintmax_t)obj->idle_timeout);
	EMIT("\"%s\":%ju,", "keepalive",
		(uintmax_t)obj->keepalive);
	EMIT("\"%s\":%ju,", "max_halfopen",
		(uintmax_t)obj->max_halfopen);
	EMIT("\"%s\":%ju,", "max_streams",
		(uintmax_t)obj->max_streams);
	EMIT_LIT("\"mem_pressure\":");
	EMIT_SUB(json_marshal_conf_mux_mem_pressure, &obj->mem_pressure);
	EMIT_LIT(",");
	EMIT_LIT("\"nodelay\":");
	if (obj->nodelay) {
		EMIT_LIT("true,");
	} else {
		EMIT_LIT("false,");
	}
	EMIT("\"%s\":%ju,", "ping_timeout",
		(uintmax_t)obj->ping_timeout);
	EMIT("\"%s\":%ju,", "resume_timeout",
		(uintmax_t)obj->resume_timeout);
	EMIT("\"%s\":%ju,", "send_timeout",
		(uintmax_t)obj->send_timeout);
	EMIT("\"%s\":%ju,", "session_window",
		(uintmax_t)obj->session_window);
	EMIT("\"%s\":%ju,", "stream_window",
		(uintmax_t)obj->stream_window);
	EMIT_LIT("\"tcp\":");
	EMIT_SUB(json_marshal_conf_mux_tcp, &obj->tcp);
	EMIT_LIT(",");

	if (n_ > n_start_) { n_--; }
	EMIT_LIT("}");

	return n_;
}

static int json_marshal_conf_identity(
	char *buf, size_t bufsz, const struct json_conf_identity *obj)
{
	int n_ = 0;
	int r_;

	EMIT_LIT("{");
	const int n_start_ = n_;

	if (obj->authcerts_json.str != NULL) {
		EMIT("\"%s\":%.*s,", "authcerts",
			(int)obj->authcerts_json.len, obj->authcerts_json.str);
	}
	if (obj->claim.str != NULL) {
		EMIT_LIT("\"claim\":");
		EMIT_STR(obj->claim.str, obj->claim.len);
		EMIT_LIT(",");
	}
	if (obj->listen_json.str != NULL) {
		EMIT("\"%s\":%.*s,", "listen",
			(int)obj->listen_json.len, obj->listen_json.str);
	}
	if (obj->mux_connect != NULL) {
		EMIT_LIT("\"mux_connect\":[");
		for (size_t i_ = 0; i_ < obj->mux_connect_count; i_++) {
			if (i_ > 0) { if (buf && bufsz > (size_t)n_) buf[n_] = ','; n_++; }
			EMIT_STR(obj->mux_connect[i_].str, obj->mux_connect[i_].len);
		}
		EMIT_LIT("],");
	}

	if (n_ > n_start_) { n_--; }
	EMIT_LIT("}");

	return n_;
}

int json_marshal_conf(
	char *buf, size_t bufsz, const struct json_conf *obj)
{
	int n_ = 0;
	int r_;

	EMIT_LIT("{");
	const int n_start_ = n_;

	if (obj->api_listen.str != NULL) {
		EMIT_LIT("\"api_listen\":");
		EMIT_STR(obj->api_listen.str, obj->api_listen.len);
		EMIT_LIT(",");
	}
	if (obj->connect.str != NULL) {
		EMIT_LIT("\"connect\":");
		EMIT_STR(obj->connect.str, obj->connect.len);
		EMIT_LIT(",");
	}
	EMIT_LIT("\"identity\":");
	EMIT_SUB(json_marshal_conf_identity, &obj->identity);
	EMIT_LIT(",");
	if (obj->listen.str != NULL) {
		EMIT_LIT("\"listen\":");
		EMIT_STR(obj->listen.str, obj->listen.len);
		EMIT_LIT(",");
	}
	EMIT("\"%s\":%ju,", "loglevel",
		(uintmax_t)obj->loglevel);
	EMIT("\"%s\":%ju,", "max_sessions",
		(uintmax_t)obj->max_sessions);
	if (obj->max_startups.str != NULL) {
		EMIT_LIT("\"max_startups\":");
		EMIT_STR(obj->max_startups.str, obj->max_startups.len);
		EMIT_LIT(",");
	}
	EMIT_LIT("\"mux\":");
	EMIT_SUB(json_marshal_conf_mux, &obj->mux);
	EMIT_LIT(",");
	if (obj->mux_connect.str != NULL) {
		EMIT_LIT("\"mux_connect\":");
		EMIT_STR(obj->mux_connect.str, obj->mux_connect.len);
		EMIT_LIT(",");
	}
	if (obj->mux_listen.str != NULL) {
		EMIT_LIT("\"mux_listen\":");
		EMIT_STR(obj->mux_listen.str, obj->mux_listen.len);
		EMIT_LIT(",");
	}
	EMIT_LIT("\"tcp\":");
	EMIT_SUB(json_marshal_conf_tcp, &obj->tcp);
	EMIT_LIT(",");
	EMIT_LIT("\"tls\":");
	EMIT_SUB(json_marshal_conf_tls, &obj->tls);
	EMIT_LIT(",");
	if (obj->type.str != NULL) {
		EMIT_LIT("\"type\":");
		EMIT_STR(obj->type.str, obj->type.len);
		EMIT_LIT(",");
	}

	if (n_ > n_start_) { n_--; }
	EMIT_LIT("}");

	return n_;
}


#undef EMIT
#undef EMIT_STR
#undef EMIT_SUB
#undef EMIT_LIT

/** @} */
