/** @file conf_schema.gen.h
 * Auto-generated by scripts/gen_schema.py from conf_schema.json -- do not edit. */
#ifndef CONF_SCHEMA_GEN_H
#define CONF_SCHEMA_GEN_H

#include "codec/json.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/** @name Struct types
 *  @{ */

struct json_conf_tls {
	struct json_string alpn;
	struct json_string cert;
	struct json_string ciphersuites;
	struct json_string key;
	struct json_string sni;

	struct json_string *authcerts;
	size_t authcerts_count;

	bool kernel_offload;
	bool socket_offload;
};

struct json_conf_tcp {
	unsigned backlog;
	uintmax_t notsent_lowat;
	uintmax_t rcvbuf;
	uintmax_t sndbuf;

	bool keepalive;
	bool nodelay;
	bool reuseport;
};

struct json_conf_mux_tcp {
	unsigned backlog;
	uintmax_t notsent_lowat;
	uintmax_t rcvbuf;
	uintmax_t sndbuf;

	bool keepalive;
	bool nodelay;
	bool reuseport;
};

struct json_conf_mux_mem_pressure {
	uintmax_t hi;
	uintmax_t lo;
};

struct json_conf_mux {
	struct json_conf_mux_mem_pressure mem_pressure;
	struct json_conf_mux_tcp tcp;

	unsigned connect_timeout;
	unsigned idle_timeout;
	unsigned keepalive;
	unsigned max_frame_size;
	unsigned max_halfopen;
	uintmax_t max_streams;
	unsigned readahead;
	unsigned resume_timeout;
	unsigned send_timeout;
	unsigned session_window;
	unsigned stream_window;

	bool nodelay;
};

struct json_conf_identity {
	struct json_string claim;

	struct json_string *mux_connect;
	size_t mux_connect_count;

	struct json_string listen_json;
};

struct json_conf {
	struct json_conf_identity identity;
	struct json_conf_mux mux;
	struct json_conf_tcp tcp;
	struct json_conf_tls tls;

	struct json_string api_listen;
	struct json_string connect;
	struct json_string listen;
	struct json_string log;
	struct json_string max_startups;
	struct json_string mux_connect;
	struct json_string mux_listen;
	struct json_string type;

	uintmax_t loglevel;
	uintmax_t max_sessions;
};

/** @} */

/** @name Unmarshal
 *  @{ */

/**
 * @brief Unmarshal JSON into *obj; modifies @p json in place.
 * @param obj Output; zeroed and given schema defaults before parsing.
 * @param json Mutable JSON; @p obj aliases it, so keep it valid in use.
 * @param length Length of @p json in bytes.
 * @return true on success; on failure, false and *obj reset to all-zero.
 */
bool json_unmarshal_conf(
	struct json_conf *obj, char *json, size_t length);

/** @} */

/** @name Marshal
 *  @{ */

/**
 * @brief Marshal *obj into @p buf as JSON (snprintf semantics).
 * @param buf Output buffer, or NULL to only compute the size.
 * @param bufsz Size of @p buf in bytes.
 * @param obj Object to encode.
 * @param indent Per-level indent for pretty output, or NULL for compact.
 * @return Byte length excluding NUL (truncates if >= @p bufsz), or -1 on error.
 */
int json_marshal_conf(
	char *buf, size_t bufsz, const struct json_conf *obj, const char *indent);

/** @} */

/** @name Free
 *  @{ */

/** @brief Free heap-allocated fields inside *obj (arrays). */
void json_free_conf(struct json_conf *obj);

/** @} */

#endif /* CONF_SCHEMA_GEN_H */
