/** @file conf_schema.gen.c
 * Auto-generated by scripts/gen_schema.py from conf_schema.json -- do not edit. */
#include "conf_schema.gen.h"

#include "codec/json.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/** @name Key tables
 *  @{ */

/* --- json_conf --- */
typedef struct { const char *name; size_t len; int idx; } json_conf_entry_;
static const json_conf_entry_ json_conf_keys_[] = {
    {"mux", 3, 7},
    {"tcp", 3, 10},
    {"tls", 3, 11},
    {"type", 4, 12},
    {"listen", 6, 3},
    {"connect", 7, 1},
    {"identity", 8, 2},
    {"loglevel", 8, 4},
    {"api_listen", 10, 0},
    {"mux_listen", 10, 9},
    {"mux_connect", 11, 8},
    {"max_sessions", 12, 5},
    {"max_startups", 12, 6},
};
static int json_conf_cmp_(const void *key_, const void *entry_)
{
    const json_conf_entry_ *k_ = (const json_conf_entry_ *)key_;
    const json_conf_entry_ *e_ = (const json_conf_entry_ *)entry_;
    if (k_->len < e_->len) { return -1; }
    if (k_->len > e_->len) { return  1; }
    return memcmp(k_->name, e_->name, k_->len);
}
static int
json_conf_lookup(const char *str, size_t len)
{
    const json_conf_entry_ key_ = {str, len, 0};
    const json_conf_entry_ *e_ =
        bsearch(&key_, json_conf_keys_, 13, sizeof(*json_conf_keys_), json_conf_cmp_);
    return e_ ? e_->idx : -1;
}

/* --- json_conf_identity --- */
static int
json_conf_identity_lookup(const char *str, size_t len)
{
    if (len < 1) { return -1; }
    switch ((unsigned char)str[0]) {
    case 'c':
        return len == 5 && memcmp(str, "claim", 5) == 0 ? 0 : -1;
    case 'l':
        return len == 6 && memcmp(str, "listen", 6) == 0 ? 1 : -1;
    case 'm':
        return len == 11 && memcmp(str, "mux_connect", 11) == 0 ? 2 : -1;
    default: return -1;
    }
}

/* --- json_conf_mux --- */
typedef struct { const char *name; size_t len; int idx; } json_conf_mux_entry_;
static const json_conf_mux_entry_ json_conf_mux_keys_[] = {
    {"tcp", 3, 12},
    {"nodelay", 7, 6},
    {"timeout", 7, 13},
    {"keepalive", 9, 2},
    {"max_streams", 11, 4},
    {"idle_timeout", 12, 1},
    {"max_halfopen", 12, 3},
    {"mem_pressure", 12, 5},
    {"ping_timeout", 12, 7},
    {"send_timeout", 12, 9},
    {"stream_window", 13, 11},
    {"resume_timeout", 14, 8},
    {"session_window", 14, 10},
    {"connect_timeout", 15, 0},
};
static int json_conf_mux_cmp_(const void *key_, const void *entry_)
{
    const json_conf_mux_entry_ *k_ = (const json_conf_mux_entry_ *)key_;
    const json_conf_mux_entry_ *e_ = (const json_conf_mux_entry_ *)entry_;
    if (k_->len < e_->len) { return -1; }
    if (k_->len > e_->len) { return  1; }
    return memcmp(k_->name, e_->name, k_->len);
}
static int
json_conf_mux_lookup(const char *str, size_t len)
{
    const json_conf_mux_entry_ key_ = {str, len, 0};
    const json_conf_mux_entry_ *e_ =
        bsearch(&key_, json_conf_mux_keys_, 14, sizeof(*json_conf_mux_keys_), json_conf_mux_cmp_);
    return e_ ? e_->idx : -1;
}

/* --- json_conf_mux_mem_pressure --- */
static int
json_conf_mux_mem_pressure_lookup(const char *str, size_t len)
{
    if (len < 1) { return -1; }
    switch ((unsigned char)str[0]) {
    case 'h':
        return len == 2 && memcmp(str, "hi", 2) == 0 ? 0 : -1;
    case 'l':
        return len == 2 && memcmp(str, "lo", 2) == 0 ? 1 : -1;
    default: return -1;
    }
}

/* --- json_conf_mux_tcp --- */
typedef struct { const char *name; size_t len; int idx; } json_conf_mux_tcp_entry_;
static const json_conf_mux_tcp_entry_ json_conf_mux_tcp_keys_[] = {
    {"rcvbuf", 6, 4},
    {"sndbuf", 6, 6},
    {"backlog", 7, 0},
    {"nodelay", 7, 2},
    {"keepalive", 9, 1},
    {"reuseport", 9, 5},
    {"notsent_lowat", 13, 3},
};
static int json_conf_mux_tcp_cmp_(const void *key_, const void *entry_)
{
    const json_conf_mux_tcp_entry_ *k_ = (const json_conf_mux_tcp_entry_ *)key_;
    const json_conf_mux_tcp_entry_ *e_ = (const json_conf_mux_tcp_entry_ *)entry_;
    if (k_->len < e_->len) { return -1; }
    if (k_->len > e_->len) { return  1; }
    return memcmp(k_->name, e_->name, k_->len);
}
static int
json_conf_mux_tcp_lookup(const char *str, size_t len)
{
    const json_conf_mux_tcp_entry_ key_ = {str, len, 0};
    const json_conf_mux_tcp_entry_ *e_ =
        bsearch(&key_, json_conf_mux_tcp_keys_, 7, sizeof(*json_conf_mux_tcp_keys_), json_conf_mux_tcp_cmp_);
    return e_ ? e_->idx : -1;
}

/* --- json_conf_tcp --- */
typedef struct { const char *name; size_t len; int idx; } json_conf_tcp_entry_;
static const json_conf_tcp_entry_ json_conf_tcp_keys_[] = {
    {"rcvbuf", 6, 4},
    {"sndbuf", 6, 6},
    {"backlog", 7, 0},
    {"nodelay", 7, 2},
    {"keepalive", 9, 1},
    {"reuseport", 9, 5},
    {"notsent_lowat", 13, 3},
};
static int json_conf_tcp_cmp_(const void *key_, const void *entry_)
{
    const json_conf_tcp_entry_ *k_ = (const json_conf_tcp_entry_ *)key_;
    const json_conf_tcp_entry_ *e_ = (const json_conf_tcp_entry_ *)entry_;
    if (k_->len < e_->len) { return -1; }
    if (k_->len > e_->len) { return  1; }
    return memcmp(k_->name, e_->name, k_->len);
}
static int
json_conf_tcp_lookup(const char *str, size_t len)
{
    const json_conf_tcp_entry_ key_ = {str, len, 0};
    const json_conf_tcp_entry_ *e_ =
        bsearch(&key_, json_conf_tcp_keys_, 7, sizeof(*json_conf_tcp_keys_), json_conf_tcp_cmp_);
    return e_ ? e_->idx : -1;
}

/* --- json_conf_tls --- */
static int
json_conf_tls_lookup(const char *str, size_t len)
{
    if (len < 3) { return -1; }
    switch ((unsigned char)str[2]) {
    case 't':
        return len == 9 && memcmp(str, "authcerts", 9) == 0 ? 0 : -1;
    case 'r':
        return len == 4 && memcmp(str, "cert", 4) == 0 ? 1 : -1;
    case 'p':
        return len == 12 && memcmp(str, "ciphersuites", 12) == 0 ? 2 : -1;
    case 'y':
        return len == 3 && memcmp(str, "key", 3) == 0 ? 3 : -1;
    default: return -1;
    }
}

/** @} */

/** @name Key indices
 *  @{ */

enum json_conf_key {
    JSON_CONF_API_LISTEN = 0,
    JSON_CONF_CONNECT = 1,
    JSON_CONF_IDENTITY = 2,
    JSON_CONF_LISTEN = 3,
    JSON_CONF_LOGLEVEL = 4,
    JSON_CONF_MAX_SESSIONS = 5,
    JSON_CONF_MAX_STARTUPS = 6,
    JSON_CONF_MUX = 7,
    JSON_CONF_MUX_CONNECT = 8,
    JSON_CONF_MUX_LISTEN = 9,
    JSON_CONF_TCP = 10,
    JSON_CONF_TLS = 11,
    JSON_CONF_TYPE = 12,
};

enum json_conf_identity_key {
    JSON_CONF_IDENTITY_CLAIM = 0,
    JSON_CONF_IDENTITY_LISTEN = 1,
    JSON_CONF_IDENTITY_MUX_CONNECT = 2,
};

enum json_conf_mux_key {
    JSON_CONF_MUX_CONNECT_TIMEOUT = 0,
    JSON_CONF_MUX_IDLE_TIMEOUT = 1,
    JSON_CONF_MUX_KEEPALIVE = 2,
    JSON_CONF_MUX_MAX_HALFOPEN = 3,
    JSON_CONF_MUX_MAX_STREAMS = 4,
    JSON_CONF_MUX_MEM_PRESSURE = 5,
    JSON_CONF_MUX_NODELAY = 6,
    JSON_CONF_MUX_PING_TIMEOUT = 7,
    JSON_CONF_MUX_RESUME_TIMEOUT = 8,
    JSON_CONF_MUX_SEND_TIMEOUT = 9,
    JSON_CONF_MUX_SESSION_WINDOW = 10,
    JSON_CONF_MUX_STREAM_WINDOW = 11,
    JSON_CONF_MUX_TCP = 12,
    JSON_CONF_MUX_TIMEOUT = 13,
};

enum json_conf_mux_mem_pressure_key {
    JSON_CONF_MUX_MEM_PRESSURE_HI = 0,
    JSON_CONF_MUX_MEM_PRESSURE_LO = 1,
};

enum json_conf_mux_tcp_key {
    JSON_CONF_MUX_TCP_BACKLOG = 0,
    JSON_CONF_MUX_TCP_KEEPALIVE = 1,
    JSON_CONF_MUX_TCP_NODELAY = 2,
    JSON_CONF_MUX_TCP_NOTSENT_LOWAT = 3,
    JSON_CONF_MUX_TCP_RCVBUF = 4,
    JSON_CONF_MUX_TCP_REUSEPORT = 5,
    JSON_CONF_MUX_TCP_SNDBUF = 6,
};

enum json_conf_tcp_key {
    JSON_CONF_TCP_BACKLOG = 0,
    JSON_CONF_TCP_KEEPALIVE = 1,
    JSON_CONF_TCP_NODELAY = 2,
    JSON_CONF_TCP_NOTSENT_LOWAT = 3,
    JSON_CONF_TCP_RCVBUF = 4,
    JSON_CONF_TCP_REUSEPORT = 5,
    JSON_CONF_TCP_SNDBUF = 6,
};

enum json_conf_tls_key {
    JSON_CONF_TLS_AUTHCERTS = 0,
    JSON_CONF_TLS_CERT = 1,
    JSON_CONF_TLS_CIPHERSUITES = 2,
    JSON_CONF_TLS_KEY = 3,
};

/** @} */

/** @name Free
 *  @{ */

static void json_conf_tls_free(struct json_conf_tls *obj)
{
    free((void *)obj->authcerts);
    free(obj->authcerts_lens);
}

static void json_conf_tcp_free(struct json_conf_tcp *obj)
{
    (void)obj;
}

static void json_conf_mux_tcp_free(struct json_conf_mux_tcp *obj)
{
    (void)obj;
}

static void json_conf_mux_mem_pressure_free(struct json_conf_mux_mem_pressure *obj)
{
    (void)obj;
}

static void json_conf_mux_free(struct json_conf_mux *obj)
{
    json_conf_mux_mem_pressure_free(&obj->mem_pressure);
    json_conf_mux_tcp_free(&obj->tcp);
}

static void json_conf_identity_free(struct json_conf_identity *obj)
{
    free(obj->listen_json);
    free((void *)obj->mux_connect);
    free(obj->mux_connect_lens);
}

void json_conf_free(struct json_conf *obj)
{
    json_conf_identity_free(&obj->identity);
    json_conf_mux_free(&obj->mux);
    json_conf_tcp_free(&obj->tcp);
    json_conf_tls_free(&obj->tls);
}

/** @} */

/** @name Unmarshal
 *  @{ */

static bool json_conf_tls_unmarshal_authcerts(
    struct json_conf_tls *obj, char *val_, size_t val_len_)
{
    const struct json_val arr_ = json_parse(val_, val_len_);
    if (arr_.type != JSON_ARRAY) { return false; }
    char **items_ = NULL;
    size_t *lens_ = NULL;
    size_t count_ = 0, cap_ = 0;
    json_iter ait_ = arr_.iter;
    char *av_; size_t alen_;
    while (json_arr_next(val_, val_len_, &ait_, &av_, &alen_)) {
        const struct json_val sv_ = json_parse(av_, alen_);
        if (sv_.type != JSON_STRING) {
            free((void *)items_);
            free(lens_);
            return false;
        }
        if (count_ >= cap_) {
            const size_t nc_ = cap_ ? cap_ * 2 : 4;
            char **na_ = (char **)realloc((void *)items_, nc_ * sizeof(*na_));
            if (na_ == NULL) {
                free((void *)items_);
                free(lens_);
                return false;
            }
            size_t *nl_ = realloc(lens_, nc_ * sizeof(*nl_));
            if (nl_ == NULL) {
                free((void *)na_);
                free(lens_);
                return false;
            }
            items_ = na_; lens_ = nl_; cap_ = nc_;
        }
        items_[count_] = sv_.str;
        lens_[count_] = sv_.len;
        count_++;
    }
    if (count_ == 0) {
        items_ = (char **)malloc(sizeof(*items_));
        if (!items_) { return false; }
    }
    obj->authcerts = items_;
    obj->authcerts_lens = lens_;
    obj->authcerts_count = count_;
    return true;
}

static bool json_conf_tls_unmarshal(
    struct json_conf_tls *obj, char *json, size_t length)
{
    const struct json_val root_ = json_parse(json, length);
    if (root_.type != JSON_OBJECT) { return false; }
    json_iter iter_ = root_.iter;
    char *key_; size_t key_len_; char *val_; size_t val_len_;
    while (json_obj_next(json, length, &iter_,
            &key_, &key_len_, &val_, &val_len_)) {
        const int k_ = json_conf_tls_lookup(key_, key_len_);
        switch (k_) {
        case JSON_CONF_TLS_AUTHCERTS: {
            if (!json_conf_tls_unmarshal_authcerts(obj, val_, val_len_)) { return false; }
            break;
        }
        case JSON_CONF_TLS_CERT: {
            if (!json_parse_string(val_, val_len_, &obj->cert, &obj->cert_len)) { return false; }
            break;
        }
        case JSON_CONF_TLS_CIPHERSUITES: {
            if (!json_parse_string(val_, val_len_, &obj->ciphersuites, &obj->ciphersuites_len)) { return false; }
            break;
        }
        case JSON_CONF_TLS_KEY: {
            if (!json_parse_string(val_, val_len_, &obj->key, &obj->key_len)) { return false; }
            break;
        }
        default:
            break;
        }
    }
    return true;
}

static bool json_conf_tcp_unmarshal(
    struct json_conf_tcp *obj, char *json, size_t length)
{
    const struct json_val root_ = json_parse(json, length);
    if (root_.type != JSON_OBJECT) { return false; }
    json_iter iter_ = root_.iter;
    char *key_; size_t key_len_; char *val_; size_t val_len_;
    while (json_obj_next(json, length, &iter_,
            &key_, &key_len_, &val_, &val_len_)) {
        const int k_ = json_conf_tcp_lookup(key_, key_len_);
        switch (k_) {
        case JSON_CONF_TCP_BACKLOG: {
            if (!json_parse_uint(val_, val_len_, &obj->backlog)) { return false; }
            obj->has_backlog = true;
            break;
        }
        case JSON_CONF_TCP_KEEPALIVE: {
            { bool bv_;
            if (!json_parse_bool(val_, val_len_, &bv_)) { return false; }
            obj->keepalive = bv_; obj->has_keepalive = true; }
            break;
        }
        case JSON_CONF_TCP_NODELAY: {
            { bool bv_;
            if (!json_parse_bool(val_, val_len_, &bv_)) { return false; }
            obj->nodelay = bv_; obj->has_nodelay = true; }
            break;
        }
        case JSON_CONF_TCP_NOTSENT_LOWAT: {
            if (!json_parse_umax(val_, val_len_, &obj->notsent_lowat)) { return false; }
            obj->has_notsent_lowat = true;
            break;
        }
        case JSON_CONF_TCP_RCVBUF: {
            if (!json_parse_umax(val_, val_len_, &obj->rcvbuf)) { return false; }
            obj->has_rcvbuf = true;
            break;
        }
        case JSON_CONF_TCP_REUSEPORT: {
            { bool bv_;
            if (!json_parse_bool(val_, val_len_, &bv_)) { return false; }
            obj->reuseport = bv_; obj->has_reuseport = true; }
            break;
        }
        case JSON_CONF_TCP_SNDBUF: {
            if (!json_parse_umax(val_, val_len_, &obj->sndbuf)) { return false; }
            obj->has_sndbuf = true;
            break;
        }
        default:
            break;
        }
    }
    return true;
}

static bool json_conf_mux_tcp_unmarshal(
    struct json_conf_mux_tcp *obj, char *json, size_t length)
{
    const struct json_val root_ = json_parse(json, length);
    if (root_.type != JSON_OBJECT) { return false; }
    json_iter iter_ = root_.iter;
    char *key_; size_t key_len_; char *val_; size_t val_len_;
    while (json_obj_next(json, length, &iter_,
            &key_, &key_len_, &val_, &val_len_)) {
        const int k_ = json_conf_mux_tcp_lookup(key_, key_len_);
        switch (k_) {
        case JSON_CONF_MUX_TCP_BACKLOG: {
            if (!json_parse_uint(val_, val_len_, &obj->backlog)) { return false; }
            obj->has_backlog = true;
            break;
        }
        case JSON_CONF_MUX_TCP_KEEPALIVE: {
            { bool bv_;
            if (!json_parse_bool(val_, val_len_, &bv_)) { return false; }
            obj->keepalive = bv_; obj->has_keepalive = true; }
            break;
        }
        case JSON_CONF_MUX_TCP_NODELAY: {
            { bool bv_;
            if (!json_parse_bool(val_, val_len_, &bv_)) { return false; }
            obj->nodelay = bv_; obj->has_nodelay = true; }
            break;
        }
        case JSON_CONF_MUX_TCP_NOTSENT_LOWAT: {
            if (!json_parse_umax(val_, val_len_, &obj->notsent_lowat)) { return false; }
            obj->has_notsent_lowat = true;
            break;
        }
        case JSON_CONF_MUX_TCP_RCVBUF: {
            if (!json_parse_umax(val_, val_len_, &obj->rcvbuf)) { return false; }
            obj->has_rcvbuf = true;
            break;
        }
        case JSON_CONF_MUX_TCP_REUSEPORT: {
            { bool bv_;
            if (!json_parse_bool(val_, val_len_, &bv_)) { return false; }
            obj->reuseport = bv_; obj->has_reuseport = true; }
            break;
        }
        case JSON_CONF_MUX_TCP_SNDBUF: {
            if (!json_parse_umax(val_, val_len_, &obj->sndbuf)) { return false; }
            obj->has_sndbuf = true;
            break;
        }
        default:
            break;
        }
    }
    return true;
}

static bool json_conf_mux_mem_pressure_unmarshal(
    struct json_conf_mux_mem_pressure *obj, char *json, size_t length)
{
    const struct json_val root_ = json_parse(json, length);
    if (root_.type != JSON_OBJECT) { return false; }
    json_iter iter_ = root_.iter;
    char *key_; size_t key_len_; char *val_; size_t val_len_;
    while (json_obj_next(json, length, &iter_,
            &key_, &key_len_, &val_, &val_len_)) {
        const int k_ = json_conf_mux_mem_pressure_lookup(key_, key_len_);
        switch (k_) {
        case JSON_CONF_MUX_MEM_PRESSURE_HI: {
            if (!json_parse_umax(val_, val_len_, &obj->hi)) { return false; }
            obj->has_hi = true;
            break;
        }
        case JSON_CONF_MUX_MEM_PRESSURE_LO: {
            if (!json_parse_umax(val_, val_len_, &obj->lo)) { return false; }
            obj->has_lo = true;
            break;
        }
        default:
            break;
        }
    }
    return true;
}

static bool json_conf_mux_unmarshal(
    struct json_conf_mux *obj, char *json, size_t length)
{
    const struct json_val root_ = json_parse(json, length);
    if (root_.type != JSON_OBJECT) { return false; }
    json_iter iter_ = root_.iter;
    char *key_; size_t key_len_; char *val_; size_t val_len_;
    while (json_obj_next(json, length, &iter_,
            &key_, &key_len_, &val_, &val_len_)) {
        const int k_ = json_conf_mux_lookup(key_, key_len_);
        switch (k_) {
        case JSON_CONF_MUX_CONNECT_TIMEOUT: {
            if (!json_parse_uint(val_, val_len_, &obj->connect_timeout)) { return false; }
            obj->has_connect_timeout = true;
            break;
        }
        case JSON_CONF_MUX_IDLE_TIMEOUT: {
            if (!json_parse_uint(val_, val_len_, &obj->idle_timeout)) { return false; }
            obj->has_idle_timeout = true;
            break;
        }
        case JSON_CONF_MUX_KEEPALIVE: {
            if (!json_parse_uint(val_, val_len_, &obj->keepalive)) { return false; }
            obj->has_keepalive = true;
            break;
        }
        case JSON_CONF_MUX_MAX_HALFOPEN: {
            if (!json_parse_uint(val_, val_len_, &obj->max_halfopen)) { return false; }
            obj->has_max_halfopen = true;
            break;
        }
        case JSON_CONF_MUX_MAX_STREAMS: {
            if (!json_parse_umax(val_, val_len_, &obj->max_streams)) { return false; }
            obj->has_max_streams = true;
            break;
        }
        case JSON_CONF_MUX_MEM_PRESSURE: {
            if (!json_conf_mux_mem_pressure_unmarshal(&obj->mem_pressure, val_, val_len_)) {
                return false;
            }
            obj->has_mem_pressure = true;
            break;
        }
        case JSON_CONF_MUX_NODELAY: {
            { bool bv_;
            if (!json_parse_bool(val_, val_len_, &bv_)) { return false; }
            obj->nodelay = bv_; obj->has_nodelay = true; }
            break;
        }
        case JSON_CONF_MUX_PING_TIMEOUT: {
            if (!json_parse_uint(val_, val_len_, &obj->ping_timeout)) { return false; }
            obj->has_ping_timeout = true;
            break;
        }
        case JSON_CONF_MUX_RESUME_TIMEOUT: {
            if (!json_parse_uint(val_, val_len_, &obj->resume_timeout)) { return false; }
            obj->has_resume_timeout = true;
            break;
        }
        case JSON_CONF_MUX_SEND_TIMEOUT: {
            if (!json_parse_uint(val_, val_len_, &obj->send_timeout)) { return false; }
            obj->has_send_timeout = true;
            break;
        }
        case JSON_CONF_MUX_SESSION_WINDOW: {
            if (!json_parse_uint(val_, val_len_, &obj->session_window)) { return false; }
            obj->has_session_window = true;
            break;
        }
        case JSON_CONF_MUX_STREAM_WINDOW: {
            if (!json_parse_uint(val_, val_len_, &obj->stream_window)) { return false; }
            obj->has_stream_window = true;
            break;
        }
        case JSON_CONF_MUX_TCP: {
            if (!json_conf_mux_tcp_unmarshal(&obj->tcp, val_, val_len_)) {
                return false;
            }
            obj->has_tcp = true;
            break;
        }
        case JSON_CONF_MUX_TIMEOUT: {
            if (!json_parse_uint(val_, val_len_, &obj->timeout)) { return false; }
            obj->has_timeout = true;
            break;
        }
        default:
            break;
        }
    }
    return true;
}

static bool json_conf_identity_unmarshal_mux_connect(
    struct json_conf_identity *obj, char *val_, size_t val_len_)
{
    const struct json_val arr_ = json_parse(val_, val_len_);
    if (arr_.type != JSON_ARRAY) { return false; }
    char **items_ = NULL;
    size_t *lens_ = NULL;
    size_t count_ = 0, cap_ = 0;
    json_iter ait_ = arr_.iter;
    char *av_; size_t alen_;
    while (json_arr_next(val_, val_len_, &ait_, &av_, &alen_)) {
        const struct json_val sv_ = json_parse(av_, alen_);
        if (sv_.type != JSON_STRING) {
            free((void *)items_);
            free(lens_);
            return false;
        }
        if (count_ >= cap_) {
            const size_t nc_ = cap_ ? cap_ * 2 : 4;
            char **na_ = (char **)realloc((void *)items_, nc_ * sizeof(*na_));
            if (na_ == NULL) {
                free((void *)items_);
                free(lens_);
                return false;
            }
            size_t *nl_ = realloc(lens_, nc_ * sizeof(*nl_));
            if (nl_ == NULL) {
                free((void *)na_);
                free(lens_);
                return false;
            }
            items_ = na_; lens_ = nl_; cap_ = nc_;
        }
        items_[count_] = sv_.str;
        lens_[count_] = sv_.len;
        count_++;
    }
    if (count_ == 0) {
        items_ = (char **)malloc(sizeof(*items_));
        if (!items_) { return false; }
    }
    obj->mux_connect = items_;
    obj->mux_connect_lens = lens_;
    obj->mux_connect_count = count_;
    return true;
}

static bool json_conf_identity_unmarshal(
    struct json_conf_identity *obj, char *json, size_t length)
{
    const struct json_val root_ = json_parse(json, length);
    if (root_.type != JSON_OBJECT) { return false; }
    json_iter iter_ = root_.iter;
    char *key_; size_t key_len_; char *val_; size_t val_len_;
    while (json_obj_next(json, length, &iter_,
            &key_, &key_len_, &val_, &val_len_)) {
        const int k_ = json_conf_identity_lookup(key_, key_len_);
        switch (k_) {
        case JSON_CONF_IDENTITY_CLAIM: {
            if (!json_parse_string(val_, val_len_, &obj->claim, &obj->claim_len)) { return false; }
            break;
        }
        case JSON_CONF_IDENTITY_LISTEN: {
            obj->listen_json = strndup(val_, val_len_);
            if (obj->listen_json == NULL) { return false; }
            obj->listen_len = val_len_;
            break;
        }
        case JSON_CONF_IDENTITY_MUX_CONNECT: {
            if (!json_conf_identity_unmarshal_mux_connect(obj, val_, val_len_)) { return false; }
            break;
        }
        default:
            break;
        }
    }
    return true;
}

bool json_conf_unmarshal(
    struct json_conf *obj, char *json, size_t length)
{
    const struct json_val root_ = json_parse(json, length);
    if (root_.type != JSON_OBJECT) { return false; }
    json_iter iter_ = root_.iter;
    char *key_; size_t key_len_; char *val_; size_t val_len_;
    while (json_obj_next(json, length, &iter_,
            &key_, &key_len_, &val_, &val_len_)) {
        const int k_ = json_conf_lookup(key_, key_len_);
        switch (k_) {
        case JSON_CONF_API_LISTEN: {
            if (!json_parse_string(val_, val_len_, &obj->api_listen, &obj->api_listen_len)) { return false; }
            break;
        }
        case JSON_CONF_CONNECT: {
            if (!json_parse_string(val_, val_len_, &obj->connect, &obj->connect_len)) { return false; }
            break;
        }
        case JSON_CONF_IDENTITY: {
            if (!json_conf_identity_unmarshal(&obj->identity, val_, val_len_)) {
                return false;
            }
            obj->has_identity = true;
            break;
        }
        case JSON_CONF_LISTEN: {
            if (!json_parse_string(val_, val_len_, &obj->listen, &obj->listen_len)) { return false; }
            break;
        }
        case JSON_CONF_LOGLEVEL: {
            if (!json_parse_uint(val_, val_len_, &obj->loglevel)) { return false; }
            obj->has_loglevel = true;
            break;
        }
        case JSON_CONF_MAX_SESSIONS: {
            if (!json_parse_umax(val_, val_len_, &obj->max_sessions)) { return false; }
            obj->has_max_sessions = true;
            break;
        }
        case JSON_CONF_MAX_STARTUPS: {
            if (!json_parse_string(val_, val_len_, &obj->max_startups, &obj->max_startups_len)) { return false; }
            break;
        }
        case JSON_CONF_MUX: {
            if (!json_conf_mux_unmarshal(&obj->mux, val_, val_len_)) {
                return false;
            }
            obj->has_mux = true;
            break;
        }
        case JSON_CONF_MUX_CONNECT: {
            if (!json_parse_string(val_, val_len_, &obj->mux_connect, &obj->mux_connect_len)) { return false; }
            break;
        }
        case JSON_CONF_MUX_LISTEN: {
            if (!json_parse_string(val_, val_len_, &obj->mux_listen, &obj->mux_listen_len)) { return false; }
            break;
        }
        case JSON_CONF_TCP: {
            if (!json_conf_tcp_unmarshal(&obj->tcp, val_, val_len_)) {
                return false;
            }
            obj->has_tcp = true;
            break;
        }
        case JSON_CONF_TLS: {
            if (!json_conf_tls_unmarshal(&obj->tls, val_, val_len_)) {
                return false;
            }
            obj->has_tls = true;
            break;
        }
        case JSON_CONF_TYPE: {
            if (!json_parse_string(val_, val_len_, &obj->type, &obj->type_len)) { return false; }
            break;
        }
        default:
            break;
        }
    }
    return true;
}

/** @} */

/** @name Marshal
 *  @{ */

#define EMIT(fmt, ...) do { \
    r_ = snprintf(buf ? buf + n_ : NULL, \
        bufsz > (size_t)n_ ? bufsz - (size_t)n_ : 0, fmt, __VA_ARGS__); \
    if (r_ < 0) { return -1; } \
    n_ += r_; \
} while (0)
#define EMIT_STR(s, len) do { \
    r_ = json_marshal_string(buf ? buf + n_ : NULL, \
        bufsz > (size_t)n_ ? bufsz - (size_t)n_ : 0, (s), (len)); \
    if (r_ < 0) { return -1; } \
    n_ += r_; \
} while (0)
#define EMIT_SUB(fn, arg) do { \
    r_ = (fn)(buf ? buf + n_ : NULL, \
        bufsz > (size_t)n_ ? bufsz - (size_t)n_ : 0, (arg)); \
    if (r_ < 0) { return -1; } \
    n_ += r_; \
} while (0)

static int json_conf_tls_marshal(
    char *buf, size_t bufsz, const struct json_conf_tls *obj)
{
    int n_ = 0;
    int r_;
    bool first_ = true;

    EMIT("%s", "{");

    if (obj->authcerts != NULL) {
        EMIT("%s\"%s\":[" , first_ ? "" : ",", "authcerts");
        first_ = false;
        for (size_t i_ = 0; i_ < obj->authcerts_count; i_++) {
            if (i_ > 0) { if (buf && bufsz > (size_t)n_) buf[n_] = ','; n_++; }
            EMIT_STR(obj->authcerts[i_], obj->authcerts_lens[i_]);
        }
        EMIT("%s", "]");
    }
    if (obj->cert != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "cert");
        first_ = false;
        EMIT_STR(obj->cert, obj->cert_len);
    }
    if (obj->ciphersuites != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "ciphersuites");
        first_ = false;
        EMIT_STR(obj->ciphersuites, obj->ciphersuites_len);
    }
    if (obj->key != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "key");
        first_ = false;
        EMIT_STR(obj->key, obj->key_len);
    }

    EMIT("%s", "}");

    return n_;
}

static int json_conf_tcp_marshal(
    char *buf, size_t bufsz, const struct json_conf_tcp *obj)
{
    int n_ = 0;
    int r_;
    bool first_ = true;

    EMIT("%s", "{");

    if (obj->has_backlog) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "backlog",
            (uintmax_t)obj->backlog);
        first_ = false;
    }
    if (obj->has_keepalive) {
        EMIT("%s\"%s\":%s", first_ ? "" : ",", "keepalive",
            obj->keepalive ? "true" : "false");
        first_ = false;
    }
    if (obj->has_nodelay) {
        EMIT("%s\"%s\":%s", first_ ? "" : ",", "nodelay",
            obj->nodelay ? "true" : "false");
        first_ = false;
    }
    if (obj->has_notsent_lowat) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "notsent_lowat",
            (uintmax_t)obj->notsent_lowat);
        first_ = false;
    }
    if (obj->has_rcvbuf) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "rcvbuf",
            (uintmax_t)obj->rcvbuf);
        first_ = false;
    }
    if (obj->has_reuseport) {
        EMIT("%s\"%s\":%s", first_ ? "" : ",", "reuseport",
            obj->reuseport ? "true" : "false");
        first_ = false;
    }
    if (obj->has_sndbuf) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "sndbuf",
            (uintmax_t)obj->sndbuf);
        first_ = false;
    }

    EMIT("%s", "}");

    return n_;
}

static int json_conf_mux_tcp_marshal(
    char *buf, size_t bufsz, const struct json_conf_mux_tcp *obj)
{
    int n_ = 0;
    int r_;
    bool first_ = true;

    EMIT("%s", "{");

    if (obj->has_backlog) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "backlog",
            (uintmax_t)obj->backlog);
        first_ = false;
    }
    if (obj->has_keepalive) {
        EMIT("%s\"%s\":%s", first_ ? "" : ",", "keepalive",
            obj->keepalive ? "true" : "false");
        first_ = false;
    }
    if (obj->has_nodelay) {
        EMIT("%s\"%s\":%s", first_ ? "" : ",", "nodelay",
            obj->nodelay ? "true" : "false");
        first_ = false;
    }
    if (obj->has_notsent_lowat) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "notsent_lowat",
            (uintmax_t)obj->notsent_lowat);
        first_ = false;
    }
    if (obj->has_rcvbuf) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "rcvbuf",
            (uintmax_t)obj->rcvbuf);
        first_ = false;
    }
    if (obj->has_reuseport) {
        EMIT("%s\"%s\":%s", first_ ? "" : ",", "reuseport",
            obj->reuseport ? "true" : "false");
        first_ = false;
    }
    if (obj->has_sndbuf) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "sndbuf",
            (uintmax_t)obj->sndbuf);
        first_ = false;
    }

    EMIT("%s", "}");

    return n_;
}

static int json_conf_mux_mem_pressure_marshal(
    char *buf, size_t bufsz, const struct json_conf_mux_mem_pressure *obj)
{
    int n_ = 0;
    int r_;
    bool first_ = true;

    EMIT("%s", "{");

    if (obj->has_hi) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "hi",
            (uintmax_t)obj->hi);
        first_ = false;
    }
    if (obj->has_lo) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "lo",
            (uintmax_t)obj->lo);
        first_ = false;
    }

    EMIT("%s", "}");

    return n_;
}

static int json_conf_mux_marshal(
    char *buf, size_t bufsz, const struct json_conf_mux *obj)
{
    int n_ = 0;
    int r_;
    bool first_ = true;

    EMIT("%s", "{");

    if (obj->has_connect_timeout) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "connect_timeout",
            (uintmax_t)obj->connect_timeout);
        first_ = false;
    }
    if (obj->has_idle_timeout) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "idle_timeout",
            (uintmax_t)obj->idle_timeout);
        first_ = false;
    }
    if (obj->has_keepalive) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "keepalive",
            (uintmax_t)obj->keepalive);
        first_ = false;
    }
    if (obj->has_max_halfopen) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "max_halfopen",
            (uintmax_t)obj->max_halfopen);
        first_ = false;
    }
    if (obj->has_max_streams) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "max_streams",
            (uintmax_t)obj->max_streams);
        first_ = false;
    }
    if (obj->has_mem_pressure) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "mem_pressure");
        first_ = false;
        EMIT_SUB(json_conf_mux_mem_pressure_marshal, &obj->mem_pressure);
    }
    if (obj->has_nodelay) {
        EMIT("%s\"%s\":%s", first_ ? "" : ",", "nodelay",
            obj->nodelay ? "true" : "false");
        first_ = false;
    }
    if (obj->has_ping_timeout) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "ping_timeout",
            (uintmax_t)obj->ping_timeout);
        first_ = false;
    }
    if (obj->has_resume_timeout) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "resume_timeout",
            (uintmax_t)obj->resume_timeout);
        first_ = false;
    }
    if (obj->has_send_timeout) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "send_timeout",
            (uintmax_t)obj->send_timeout);
        first_ = false;
    }
    if (obj->has_session_window) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "session_window",
            (uintmax_t)obj->session_window);
        first_ = false;
    }
    if (obj->has_stream_window) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "stream_window",
            (uintmax_t)obj->stream_window);
        first_ = false;
    }
    if (obj->has_tcp) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "tcp");
        first_ = false;
        EMIT_SUB(json_conf_mux_tcp_marshal, &obj->tcp);
    }
    if (obj->has_timeout) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "timeout",
            (uintmax_t)obj->timeout);
        first_ = false;
    }

    EMIT("%s", "}");

    return n_;
}

static int json_conf_identity_marshal(
    char *buf, size_t bufsz, const struct json_conf_identity *obj)
{
    int n_ = 0;
    int r_;
    bool first_ = true;

    EMIT("%s", "{");

    if (obj->claim != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "claim");
        first_ = false;
        EMIT_STR(obj->claim, obj->claim_len);
    }
    if (obj->listen_json != NULL) {
        EMIT("%s\"%s\":%.*s", first_ ? "" : ",", "listen",
            (int)obj->listen_len, obj->listen_json);
        first_ = false;
    }
    if (obj->mux_connect != NULL) {
        EMIT("%s\"%s\":[" , first_ ? "" : ",", "mux_connect");
        first_ = false;
        for (size_t i_ = 0; i_ < obj->mux_connect_count; i_++) {
            if (i_ > 0) { if (buf && bufsz > (size_t)n_) buf[n_] = ','; n_++; }
            EMIT_STR(obj->mux_connect[i_], obj->mux_connect_lens[i_]);
        }
        EMIT("%s", "]");
    }

    EMIT("%s", "}");

    return n_;
}

int json_conf_marshal(
    char *buf, size_t bufsz, const struct json_conf *obj)
{
    int n_ = 0;
    int r_;
    bool first_ = true;

    EMIT("%s", "{");

    if (obj->api_listen != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "api_listen");
        first_ = false;
        EMIT_STR(obj->api_listen, obj->api_listen_len);
    }
    if (obj->connect != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "connect");
        first_ = false;
        EMIT_STR(obj->connect, obj->connect_len);
    }
    if (obj->has_identity) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "identity");
        first_ = false;
        EMIT_SUB(json_conf_identity_marshal, &obj->identity);
    }
    if (obj->listen != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "listen");
        first_ = false;
        EMIT_STR(obj->listen, obj->listen_len);
    }
    if (obj->has_loglevel) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "loglevel",
            (uintmax_t)obj->loglevel);
        first_ = false;
    }
    if (obj->has_max_sessions) {
        EMIT("%s\"%s\":%ju", first_ ? "" : ",", "max_sessions",
            (uintmax_t)obj->max_sessions);
        first_ = false;
    }
    if (obj->max_startups != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "max_startups");
        first_ = false;
        EMIT_STR(obj->max_startups, obj->max_startups_len);
    }
    if (obj->has_mux) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "mux");
        first_ = false;
        EMIT_SUB(json_conf_mux_marshal, &obj->mux);
    }
    if (obj->mux_connect != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "mux_connect");
        first_ = false;
        EMIT_STR(obj->mux_connect, obj->mux_connect_len);
    }
    if (obj->mux_listen != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "mux_listen");
        first_ = false;
        EMIT_STR(obj->mux_listen, obj->mux_listen_len);
    }
    if (obj->has_tcp) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "tcp");
        first_ = false;
        EMIT_SUB(json_conf_tcp_marshal, &obj->tcp);
    }
    if (obj->has_tls) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "tls");
        first_ = false;
        EMIT_SUB(json_conf_tls_marshal, &obj->tls);
    }
    if (obj->type != NULL) {
        EMIT("%s\"%s\":", first_ ? "" : ",", "type");
        first_ = false;
        EMIT_STR(obj->type, obj->type_len);
    }

    EMIT("%s", "}");

    return n_;
}


#undef EMIT
#undef EMIT_STR
#undef EMIT_SUB

/** @} */
