/** @file conf_schema.gen.c
 * Auto-generated by scripts/gen_schema.py from conf_schema.json -- do not edit. */
#include "conf_schema.gen.h"

#include "codec/json.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/** @name Key tables
 *  @{ */

/* --- json_conf --- */
typedef struct { const char *name; size_t len; int idx; } json_lookup_conf_entry_;
static const json_lookup_conf_entry_ json_lookup_conf_keys_[] = {
	{"log", 3, 4},
	{"mux", 3, 8},
	{"tcp", 3, 11},
	{"tls", 3, 12},
	{"type", 4, 13},
	{"listen", 6, 3},
	{"connect", 7, 1},
	{"identity", 8, 2},
	{"loglevel", 8, 5},
	{"api_listen", 10, 0},
	{"mux_listen", 10, 10},
	{"mux_connect", 11, 9},
	{"max_sessions", 12, 6},
	{"max_startups", 12, 7},
};
static int json_lookup_conf_cmp_(const void *key_, const void *entry_)
{
	const json_lookup_conf_entry_ *k_ = (const json_lookup_conf_entry_ *)key_;
	const json_lookup_conf_entry_ *e_ = (const json_lookup_conf_entry_ *)entry_;
	if (k_->len < e_->len) { return -1; }
	if (k_->len > e_->len) { return  1; }
	return memcmp(k_->name, e_->name, k_->len);
}
static int
json_lookup_conf(const char *str, size_t len)
{
	const json_lookup_conf_entry_ key_ = {str, len, 0};
	const json_lookup_conf_entry_ *e_ =
		bsearch(&key_, json_lookup_conf_keys_, 14, sizeof(*json_lookup_conf_keys_), json_lookup_conf_cmp_);
	return e_ ? e_->idx : -1;
}

/* --- json_conf_identity --- */
static int
json_lookup_conf_identity(const char *str, size_t len)
{
	if (len < 1) { return -1; }
	switch ((unsigned char)str[0]) {
	case 'c':
		return len == 5 && memcmp(str, "claim", 5) == 0 ? 0 : -1;
	case 'l':
		return len == 6 && memcmp(str, "listen", 6) == 0 ? 1 : -1;
	case 'm':
		return len == 11 && memcmp(str, "mux_connect", 11) == 0 ? 2 : -1;
	default: return -1;
	}
}

/* --- json_conf_mux --- */
typedef struct { const char *name; size_t len; int idx; } json_lookup_conf_mux_entry_;
static const json_lookup_conf_mux_entry_ json_lookup_conf_mux_keys_[] = {
	{"tcp", 3, 12},
	{"nodelay", 7, 7},
	{"keepalive", 9, 2},
	{"max_streams", 11, 5},
	{"idle_timeout", 12, 1},
	{"max_halfopen", 12, 4},
	{"mem_pressure", 12, 6},
	{"send_timeout", 12, 9},
	{"stream_window", 13, 11},
	{"max_frame_size", 14, 3},
	{"resume_timeout", 14, 8},
	{"session_window", 14, 10},
	{"connect_timeout", 15, 0},
};
static int json_lookup_conf_mux_cmp_(const void *key_, const void *entry_)
{
	const json_lookup_conf_mux_entry_ *k_ = (const json_lookup_conf_mux_entry_ *)key_;
	const json_lookup_conf_mux_entry_ *e_ = (const json_lookup_conf_mux_entry_ *)entry_;
	if (k_->len < e_->len) { return -1; }
	if (k_->len > e_->len) { return  1; }
	return memcmp(k_->name, e_->name, k_->len);
}
static int
json_lookup_conf_mux(const char *str, size_t len)
{
	const json_lookup_conf_mux_entry_ key_ = {str, len, 0};
	const json_lookup_conf_mux_entry_ *e_ =
		bsearch(&key_, json_lookup_conf_mux_keys_, 13, sizeof(*json_lookup_conf_mux_keys_), json_lookup_conf_mux_cmp_);
	return e_ ? e_->idx : -1;
}

/* --- json_conf_mux_mem_pressure --- */
static int
json_lookup_conf_mux_mem_pressure(const char *str, size_t len)
{
	if (len < 1) { return -1; }
	switch ((unsigned char)str[0]) {
	case 'h':
		return len == 2 && memcmp(str, "hi", 2) == 0 ? 0 : -1;
	case 'l':
		return len == 2 && memcmp(str, "lo", 2) == 0 ? 1 : -1;
	default: return -1;
	}
}

/* --- json_conf_mux_tcp --- */
typedef struct { const char *name; size_t len; int idx; } json_lookup_conf_mux_tcp_entry_;
static const json_lookup_conf_mux_tcp_entry_ json_lookup_conf_mux_tcp_keys_[] = {
	{"rcvbuf", 6, 4},
	{"sndbuf", 6, 6},
	{"backlog", 7, 0},
	{"nodelay", 7, 2},
	{"keepalive", 9, 1},
	{"reuseport", 9, 5},
	{"notsent_lowat", 13, 3},
};
static int json_lookup_conf_mux_tcp_cmp_(const void *key_, const void *entry_)
{
	const json_lookup_conf_mux_tcp_entry_ *k_ = (const json_lookup_conf_mux_tcp_entry_ *)key_;
	const json_lookup_conf_mux_tcp_entry_ *e_ = (const json_lookup_conf_mux_tcp_entry_ *)entry_;
	if (k_->len < e_->len) { return -1; }
	if (k_->len > e_->len) { return  1; }
	return memcmp(k_->name, e_->name, k_->len);
}
static int
json_lookup_conf_mux_tcp(const char *str, size_t len)
{
	const json_lookup_conf_mux_tcp_entry_ key_ = {str, len, 0};
	const json_lookup_conf_mux_tcp_entry_ *e_ =
		bsearch(&key_, json_lookup_conf_mux_tcp_keys_, 7, sizeof(*json_lookup_conf_mux_tcp_keys_), json_lookup_conf_mux_tcp_cmp_);
	return e_ ? e_->idx : -1;
}

/* --- json_conf_tcp --- */
typedef struct { const char *name; size_t len; int idx; } json_lookup_conf_tcp_entry_;
static const json_lookup_conf_tcp_entry_ json_lookup_conf_tcp_keys_[] = {
	{"rcvbuf", 6, 4},
	{"sndbuf", 6, 6},
	{"backlog", 7, 0},
	{"nodelay", 7, 2},
	{"keepalive", 9, 1},
	{"reuseport", 9, 5},
	{"notsent_lowat", 13, 3},
};
static int json_lookup_conf_tcp_cmp_(const void *key_, const void *entry_)
{
	const json_lookup_conf_tcp_entry_ *k_ = (const json_lookup_conf_tcp_entry_ *)key_;
	const json_lookup_conf_tcp_entry_ *e_ = (const json_lookup_conf_tcp_entry_ *)entry_;
	if (k_->len < e_->len) { return -1; }
	if (k_->len > e_->len) { return  1; }
	return memcmp(k_->name, e_->name, k_->len);
}
static int
json_lookup_conf_tcp(const char *str, size_t len)
{
	const json_lookup_conf_tcp_entry_ key_ = {str, len, 0};
	const json_lookup_conf_tcp_entry_ *e_ =
		bsearch(&key_, json_lookup_conf_tcp_keys_, 7, sizeof(*json_lookup_conf_tcp_keys_), json_lookup_conf_tcp_cmp_);
	return e_ ? e_->idx : -1;
}

/* --- json_conf_tls --- */
typedef struct { const char *name; size_t len; int idx; } json_lookup_conf_tls_entry_;
static const json_lookup_conf_tls_entry_ json_lookup_conf_tls_keys_[] = {
	{"key", 3, 5},
	{"sni", 3, 7},
	{"alpn", 4, 0},
	{"cert", 4, 2},
	{"authcerts", 9, 1},
	{"readahead", 9, 6},
	{"ciphersuites", 12, 3},
	{"kernel_offload", 14, 4},
	{"socket_offload", 14, 8},
};
static int json_lookup_conf_tls_cmp_(const void *key_, const void *entry_)
{
	const json_lookup_conf_tls_entry_ *k_ = (const json_lookup_conf_tls_entry_ *)key_;
	const json_lookup_conf_tls_entry_ *e_ = (const json_lookup_conf_tls_entry_ *)entry_;
	if (k_->len < e_->len) { return -1; }
	if (k_->len > e_->len) { return  1; }
	return memcmp(k_->name, e_->name, k_->len);
}
static int
json_lookup_conf_tls(const char *str, size_t len)
{
	const json_lookup_conf_tls_entry_ key_ = {str, len, 0};
	const json_lookup_conf_tls_entry_ *e_ =
		bsearch(&key_, json_lookup_conf_tls_keys_, 9, sizeof(*json_lookup_conf_tls_keys_), json_lookup_conf_tls_cmp_);
	return e_ ? e_->idx : -1;
}

/** @} */

/** @name Schema tables
 *  @{ */

static const struct json_constraint json_conf_tls_authcerts_c = {
	.flags = JSON_C_MIN_ITEMS,
	.min_items = 1,
};
static const struct json_constraint json_conf_tls_readahead_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(16777216) },
};
static const struct json_conf_tls json_conf_tls_defaults = {
	.kernel_offload = false,
	.readahead = 131072u,
	.sni = { .str = "example.com", .len = 11 },
	.socket_offload = false,
};
static const struct json_field json_conf_tls_fields[] = {
	{ .name = "alpn", .name_len = 4, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf_tls, alpn) },
	{ .name = "authcerts", .name_len = 9, .kind = JSON_K_STRING, .is_array = true, .req_bit = -1, .offset = offsetof(struct json_conf_tls, authcerts), .count_offset = offsetof(struct json_conf_tls, authcerts_count), .constraint = &json_conf_tls_authcerts_c },
	{ .name = "cert", .name_len = 4, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf_tls, cert) },
	{ .name = "ciphersuites", .name_len = 12, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf_tls, ciphersuites) },
	{ .name = "kernel_offload", .name_len = 14, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_tls, kernel_offload) },
	{ .name = "key", .name_len = 3, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf_tls, key) },
	{ .name = "readahead", .name_len = 9, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_tls, readahead), .constraint = &json_conf_tls_readahead_c },
	{ .name = "sni", .name_len = 3, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf_tls, sni) },
	{ .name = "socket_offload", .name_len = 14, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_tls, socket_offload) },
};
static const struct json_schema json_conf_tls_schema = {
	.fields = json_conf_tls_fields,
	.n_fields = 9,
	.obj_size = sizeof(struct json_conf_tls),
	.lookup = json_lookup_conf_tls,
	.defaults = &json_conf_tls_defaults,
	.present_field = -1,
};

static const struct json_constraint json_conf_tcp_backlog_c = {
	.flags = JSON_C_MIN | JSON_C_MAX,
	.u = { .min = UINTMAX_C(1), .max = UINTMAX_C(4096) },
};
static const struct json_conf_tcp json_conf_tcp_defaults = {
	.backlog = 16u,
	.keepalive = true,
	.nodelay = true,
	.notsent_lowat = UINTMAX_C(0),
	.reuseport = false,
};
static const struct json_field json_conf_tcp_fields[] = {
	{ .name = "backlog", .name_len = 7, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, backlog), .constraint = &json_conf_tcp_backlog_c },
	{ .name = "keepalive", .name_len = 9, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, keepalive) },
	{ .name = "nodelay", .name_len = 7, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, nodelay) },
	{ .name = "notsent_lowat", .name_len = 13, .kind = JSON_K_UMAX, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, notsent_lowat) },
	{ .name = "rcvbuf", .name_len = 6, .kind = JSON_K_UMAX, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, rcvbuf) },
	{ .name = "reuseport", .name_len = 9, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, reuseport) },
	{ .name = "sndbuf", .name_len = 6, .kind = JSON_K_UMAX, .req_bit = -1, .offset = offsetof(struct json_conf_tcp, sndbuf) },
};
static const struct json_schema json_conf_tcp_schema = {
	.fields = json_conf_tcp_fields,
	.n_fields = 7,
	.obj_size = sizeof(struct json_conf_tcp),
	.lookup = json_lookup_conf_tcp,
	.defaults = &json_conf_tcp_defaults,
	.present_field = -1,
};

static const struct json_constraint json_conf_mux_tcp_backlog_c = {
	.flags = JSON_C_MIN | JSON_C_MAX,
	.u = { .min = UINTMAX_C(1), .max = UINTMAX_C(4096) },
};
static const struct json_conf_mux_tcp json_conf_mux_tcp_defaults = {
	.backlog = 16u,
	.keepalive = false,
	.nodelay = true,
	.notsent_lowat = UINTMAX_C(131072),
	.reuseport = false,
};
static const struct json_field json_conf_mux_tcp_fields[] = {
	{ .name = "backlog", .name_len = 7, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_mux_tcp, backlog), .constraint = &json_conf_mux_tcp_backlog_c },
	{ .name = "keepalive", .name_len = 9, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_mux_tcp, keepalive) },
	{ .name = "nodelay", .name_len = 7, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_mux_tcp, nodelay) },
	{ .name = "notsent_lowat", .name_len = 13, .kind = JSON_K_UMAX, .req_bit = -1, .offset = offsetof(struct json_conf_mux_tcp, notsent_lowat) },
	{ .name = "rcvbuf", .name_len = 6, .kind = JSON_K_UMAX, .req_bit = -1, .offset = offsetof(struct json_conf_mux_tcp, rcvbuf) },
	{ .name = "reuseport", .name_len = 9, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_mux_tcp, reuseport) },
	{ .name = "sndbuf", .name_len = 6, .kind = JSON_K_UMAX, .req_bit = -1, .offset = offsetof(struct json_conf_mux_tcp, sndbuf) },
};
static const struct json_schema json_conf_mux_tcp_schema = {
	.fields = json_conf_mux_tcp_fields,
	.n_fields = 7,
	.obj_size = sizeof(struct json_conf_mux_tcp),
	.lookup = json_lookup_conf_mux_tcp,
	.defaults = &json_conf_mux_tcp_defaults,
	.present_field = -1,
};

static const struct json_conf_mux_mem_pressure json_conf_mux_mem_pressure_defaults = {
	.hi = UINTMAX_C(0),
	.lo = UINTMAX_C(0),
};
static const struct json_field json_conf_mux_mem_pressure_fields[] = {
	{ .name = "hi", .name_len = 2, .kind = JSON_K_UMAX, .req_bit = -1, .offset = offsetof(struct json_conf_mux_mem_pressure, hi) },
	{ .name = "lo", .name_len = 2, .kind = JSON_K_UMAX, .req_bit = -1, .offset = offsetof(struct json_conf_mux_mem_pressure, lo) },
};
static const struct json_schema json_conf_mux_mem_pressure_schema = {
	.fields = json_conf_mux_mem_pressure_fields,
	.n_fields = 2,
	.obj_size = sizeof(struct json_conf_mux_mem_pressure),
	.lookup = json_lookup_conf_mux_mem_pressure,
	.defaults = &json_conf_mux_mem_pressure_defaults,
	.present_field = -1,
};

static const struct json_constraint json_conf_mux_connect_timeout_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(86400) },
};
static const struct json_constraint json_conf_mux_idle_timeout_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(86400) },
};
static const struct json_constraint json_conf_mux_keepalive_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(86400) },
};
static const struct json_constraint json_conf_mux_max_frame_size_c = {
	.flags = JSON_C_MIN | JSON_C_MAX,
	.u = { .min = UINTMAX_C(1024), .max = UINTMAX_C(65543) },
};
static const struct json_constraint json_conf_mux_max_halfopen_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(4096) },
};
static const struct json_constraint json_conf_mux_resume_timeout_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(86400) },
};
static const struct json_constraint json_conf_mux_send_timeout_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(86400) },
};
static const struct json_constraint json_conf_mux_session_window_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(1073725440) },
};
static const struct json_constraint json_conf_mux_stream_window_c = {
	.flags = JSON_C_MAX,
	.u = { .max = UINTMAX_C(1073725440) },
};
static const struct json_conf_mux json_conf_mux_defaults = {
	.connect_timeout = 15u,
	.idle_timeout = 0u,
	.keepalive = 7200u,
	.max_frame_size = 16384u,
	.max_halfopen = 256u,
	.mem_pressure = {
		.hi = UINTMAX_C(0),
		.lo = UINTMAX_C(0),
	},
	.nodelay = true,
	.resume_timeout = 600u,
	.send_timeout = 15u,
	.session_window = 0u,
	.stream_window = 0u,
	.tcp = {
		.backlog = 16u,
		.keepalive = false,
		.nodelay = true,
		.notsent_lowat = UINTMAX_C(131072),
		.reuseport = false,
	},
};
static const struct json_field json_conf_mux_fields[] = {
	{ .name = "connect_timeout", .name_len = 15, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_mux, connect_timeout), .constraint = &json_conf_mux_connect_timeout_c },
	{ .name = "idle_timeout", .name_len = 12, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_mux, idle_timeout), .constraint = &json_conf_mux_idle_timeout_c },
	{ .name = "keepalive", .name_len = 9, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_mux, keepalive), .constraint = &json_conf_mux_keepalive_c },
	{ .name = "max_frame_size", .name_len = 14, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_mux, max_frame_size), .constraint = &json_conf_mux_max_frame_size_c },
	{ .name = "max_halfopen", .name_len = 12, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_mux, max_halfopen), .constraint = &json_conf_mux_max_halfopen_c },
	{ .name = "max_streams", .name_len = 11, .kind = JSON_K_UMAX, .req_bit = -1, .offset = offsetof(struct json_conf_mux, max_streams) },
	{ .name = "mem_pressure", .name_len = 12, .kind = JSON_K_OBJECT, .req_bit = -1, .offset = offsetof(struct json_conf_mux, mem_pressure), .child = &json_conf_mux_mem_pressure_schema },
	{ .name = "nodelay", .name_len = 7, .kind = JSON_K_BOOL, .req_bit = -1, .offset = offsetof(struct json_conf_mux, nodelay) },
	{ .name = "resume_timeout", .name_len = 14, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_mux, resume_timeout), .constraint = &json_conf_mux_resume_timeout_c },
	{ .name = "send_timeout", .name_len = 12, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_mux, send_timeout), .constraint = &json_conf_mux_send_timeout_c },
	{ .name = "session_window", .name_len = 14, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_mux, session_window), .constraint = &json_conf_mux_session_window_c },
	{ .name = "stream_window", .name_len = 13, .kind = JSON_K_UINT, .req_bit = -1, .offset = offsetof(struct json_conf_mux, stream_window), .constraint = &json_conf_mux_stream_window_c },
	{ .name = "tcp", .name_len = 3, .kind = JSON_K_OBJECT, .req_bit = -1, .offset = offsetof(struct json_conf_mux, tcp), .child = &json_conf_mux_tcp_schema },
};
static const struct json_schema json_conf_mux_schema = {
	.fields = json_conf_mux_fields,
	.n_fields = 13,
	.obj_size = sizeof(struct json_conf_mux),
	.lookup = json_lookup_conf_mux,
	.defaults = &json_conf_mux_defaults,
	.present_field = -1,
};

static const struct json_field json_conf_identity_fields[] = {
	{ .name = "claim", .name_len = 5, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf_identity, claim) },
	{ .name = "listen", .name_len = 6, .kind = JSON_K_DYNAMIC, .req_bit = -1, .offset = offsetof(struct json_conf_identity, listen_json) },
	{ .name = "mux_connect", .name_len = 11, .kind = JSON_K_STRING, .is_array = true, .req_bit = -1, .offset = offsetof(struct json_conf_identity, mux_connect), .count_offset = offsetof(struct json_conf_identity, mux_connect_count) },
};
static const struct json_schema json_conf_identity_schema = {
	.fields = json_conf_identity_fields,
	.n_fields = 3,
	.obj_size = sizeof(struct json_conf_identity),
	.lookup = json_lookup_conf_identity,
	.present_field = -1,
};

static const struct json_string json_conf_log_enum[] = {
	{ .len = 6, .str = "stdout" },
	{ .len = 6, .str = "stderr" },
	{ .len = 6, .str = "syslog" },
	{ .len = 7, .str = "discard" },
};
static const struct json_constraint json_conf_log_c = {
	.flags = JSON_C_ENUM,
	.str = { .enums = json_conf_log_enum, .n_enum = 4 },
};
static const struct json_constraint json_conf_type_c = {
	.flags = JSON_C_CONST,
	.str = { .konst = { .len = 42, .str = "application/x-multiplexd-config; version=1" } },
};
static const struct json_conf json_conf_defaults = {
	.loglevel = UINTMAX_C(4),
	.mux = {
		.connect_timeout = 15u,
		.idle_timeout = 0u,
		.keepalive = 7200u,
		.max_frame_size = 16384u,
		.max_halfopen = 256u,
		.mem_pressure = {
			.hi = UINTMAX_C(0),
			.lo = UINTMAX_C(0),
		},
		.nodelay = true,
		.resume_timeout = 600u,
		.send_timeout = 15u,
		.session_window = 0u,
		.stream_window = 0u,
		.tcp = {
			.backlog = 16u,
			.keepalive = false,
			.nodelay = true,
			.notsent_lowat = UINTMAX_C(131072),
			.reuseport = false,
		},
	},
	.tcp = {
		.backlog = 16u,
		.keepalive = true,
		.nodelay = true,
		.notsent_lowat = UINTMAX_C(0),
		.reuseport = false,
	},
	.tls = {
		.kernel_offload = false,
		.readahead = 131072u,
		.sni = { .str = "example.com", .len = 11 },
		.socket_offload = false,
	},
};
static const struct json_field json_conf_fields[] = {
	{ .name = "api_listen", .name_len = 10, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, api_listen) },
	{ .name = "connect", .name_len = 7, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, connect) },
	{ .name = "identity", .name_len = 8, .kind = JSON_K_OBJECT, .req_bit = -1, .offset = offsetof(struct json_conf, identity), .child = &json_conf_identity_schema },
	{ .name = "listen", .name_len = 6, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, listen) },
	{ .name = "log", .name_len = 3, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, log), .constraint = &json_conf_log_c },
	{ .name = "loglevel", .name_len = 8, .kind = JSON_K_UMAX, .req_bit = -1, .offset = offsetof(struct json_conf, loglevel) },
	{ .name = "max_sessions", .name_len = 12, .kind = JSON_K_UMAX, .req_bit = -1, .offset = offsetof(struct json_conf, max_sessions) },
	{ .name = "max_startups", .name_len = 12, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, max_startups) },
	{ .name = "mux", .name_len = 3, .kind = JSON_K_OBJECT, .req_bit = -1, .offset = offsetof(struct json_conf, mux), .child = &json_conf_mux_schema },
	{ .name = "mux_connect", .name_len = 11, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, mux_connect) },
	{ .name = "mux_listen", .name_len = 10, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, mux_listen) },
	{ .name = "tcp", .name_len = 3, .kind = JSON_K_OBJECT, .req_bit = -1, .offset = offsetof(struct json_conf, tcp), .child = &json_conf_tcp_schema },
	{ .name = "tls", .name_len = 3, .kind = JSON_K_OBJECT, .req_bit = -1, .offset = offsetof(struct json_conf, tls), .child = &json_conf_tls_schema },
	{ .name = "type", .name_len = 4, .kind = JSON_K_STRING, .req_bit = -1, .offset = offsetof(struct json_conf, type), .constraint = &json_conf_type_c },
};
static const struct json_schema json_conf_schema = {
	.fields = json_conf_fields,
	.n_fields = 14,
	.obj_size = sizeof(struct json_conf),
	.lookup = json_lookup_conf,
	.defaults = &json_conf_defaults,
	.present_field = -1,
};

/** @} */

/** @name Codec functions
 *  @{ */

void json_free_conf(struct json_conf *obj)
{
	json_free(&json_conf_schema, obj);
}

bool json_unmarshal_conf(
	struct json_conf *obj, char *json, size_t length)
{
	return json_unmarshal(&json_conf_schema, obj, json, length);
}

int json_marshal_conf(
	char *buf, size_t bufsz, const struct json_conf *obj, const char *indent)
{
	return json_marshal(&json_conf_schema, buf, bufsz, obj, indent);
}

/** @} */
